### ISSUE TITLE
Any plan to also support lint?

### ISSUE THREAD

**Issue by linrongbin16** [stevearc/conform.nvim#1]
Hi, do you have plan to also support lint? make it just like null-ls?

And also plan to integrate with mason?

**Comment by stevearc** [comment]
Nope! I think [nvim-lint](https://github.com/mfussenegger/nvim-lint) does an excellent job of linting already, so there's no point in duplicating that work.

I also don't have plans to integrate with mason, but I'm not opposed to the idea. It looks like the pattern for third-party integrations is to create a separate plugin, so anyone could do it if they were so inclined.
