### ISSUE TITLE
feature request: use `shiftwidth` and `expandtab` settings when invoking formatters

### ISSUE THREAD

**Issue by p00f** [stevearc/conform.nvim#102]
### Neovim version (nvim -v)

0.10.0 commit 09a17f91d0d362c6e58bfdbe3ccdeacffb0b44b9

### Operating system/version

Arch Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

NA

### Describe the bug

conform should use the `shiftwidth` and `expandtab` settings when invoking formatters

For example,
https://github.com/stevearc/conform.nvim/blob/cb87cab7a6baa6192bf13123c2a5af6fd059d62c/lua/conform/formatters/stylua.lua#L9

should use `--indent-width` and `--indent-type` with values using `shiftwidth` and `expandtab` respectively

### Steps To Reproduce

NA

### Expected Behavior

NA

**Comment by gegoune** [comment]
There is some merit here but formatters' configuration should take precedence; can't assume everyone on the project uses nvim with correctly configured tab/space settings.

**Comment by stevearc** [comment]
For many formatters, these options are set in a configuration file. If we tried to magically overwrite them in the args, we run the risk of conflicting with the actual source of truth. This would require a huge amount of effort (customizations for every formatter) for questionable benefit. Closing as out of scope. This is better left to a customization by the end user.

**Comment by wookayin** [comment]
Such a config should be done formatter by formatter.

Example:

```lua
local function shiftwidth(buf) return vim.api.nvim_get_option_value('shiftwidth', { buf = buf }) end

require("conform").formatters.shfmt = function(bufnr)
  return {
    prepend_args = { "--indent", tostring(shiftwidth(bufnr)) },
  }
  end
```

This way one can read the current value of `&shiftwidth` (i.e. indent size) and pass such a "dynamic" value to the command line of the formatter program.
