### ISSUE TITLE
bug: phpcbf discarding unsaved changes on format

### ISSUE THREAD

**Issue by star-szr** [stevearc/conform.nvim#105]
### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

macOS 13.5.2

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

14:01:38[DEBUG] Running formatters on /Users/scott/Code/conform-phpcbf/example.php: { "phpcbf" }
14:01:38[INFO] Run phpcbf on /Users/scott/Code/conform-phpcbf/example.php
14:01:38[DEBUG] Run command: { "/Users/scott/Code/conform-phpcbf/vendor/bin/phpcbf", "-q", "--stdin-path=", "/Users/scott/Code/conform-phpcbf/example.php", "-" }
14:01:38[DEBUG] phpcbf exited with code 1

### Describe the bug

Follow-up to #103.

When making a change to a line in a PHP file, unsaved changes are lost when formatting via phpcbf.

### Steps To Reproduce

1. nvim -u repro.lua
2. `:e example.php`
3. Change the name of the 'example' variable on line 3 to something else like 'conform'.
4. `:w`

### Expected Behavior

The expected behaviour would be that the edit made to line 3 is preserved when formatting on save.

The actual behaviour is that line 3 stays as ‘example’, and unsaved changes are lost. 

### Minimal example file

```php
<?php

$example = true;
```

#### Minimal composer.json

```json
{
    "name": "test/conform-phpcbf",
    "type": "project",
    "require": {
        "squizlabs/php_codesniffer": "^3.7"
    }
}
```

Run `composer install` once the composer.json above is in place.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
        format_on_save = {
          -- phpcbf is slow.
          timeout_ms = 1000,
          lsp_fallback = true,
        },
        formatters_by_ft = {
          php = { "phpcbf" },
        },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Can you try #108 and see if that fixes it for you?
