### ISSUE TITLE
bug: All formatters fail when injected formatter fails

### ISSUE THREAD

**Issue by ribru17** [stevearc/conform.nvim#111]
### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1694285958

### Operating system/version

Arch Linux 6.5.5-arch1-1

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /home/rileyb/.local/state/nvim/conform.log
            XDG_CONFIG_HOME = "/home/rileyb/.config/nvim/"
          }
          20:59:45[INFO] stylua exited with code 2
          20:59:45[DEBUG] stylua stdout: { "" }
          20:59:45[DEBUG] stylua stderr: { "error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `>`. (starting from line 1, character 1 and ending on line 1, character 2)", "additional information: leftover token", "" }
          20:59:45[ERROR] Formatter 'stylua' error: error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `>`. (starting from line 1, character 1 and ending on line 1, character 2)
          additional information: leftover token
          
          20:59:45[ERROR] Formatter 'stylua' error: error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `>`. (starting from line 1, character 1 and ending on line 1, character 2)
          additional information: leftover token

Formatters for this buffer:
deno_fmt ready (javascript, javascriptreact, typescriptreact, markdown, typescript, jsonc, json)
injected ready (markdown)

Other formatters:
clang_format ready (c, cpp)
prettierd ready (css, html)
stylua ready (luau, lua)

### Describe the bug

When using injected formatters, if an injected formatter fails then the main formatter(s) will not run. For example if an injected code block in a Markdown document cannot be formatted, the entire Markdown document will not be formatted.

### Steps To Reproduce

1. `nvim -u repro.lua`
2. Open a file with injected formatting that will fail
3. Save the file

### Expected Behavior

The Lua code will not be formatted, but the rest of the markdown document will

### Minimal example file

````md
# Hi

   wrongly indented text

> ```lua
> require('hi')
> ```

The above cannot be formatted since it is in a block quote :)
````

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs { 'config', 'data', 'state', 'cache' } do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  'folke/tokyonight.nvim',
  {
    'stevearc/conform.nvim',
    config = function()
      require('conform').setup {
        log_level = vim.log.levels.DEBUG,
        format_on_save = {
          timeout_ms = 1000,
          lsp_fallback = false,
          quiet = true,
        },
        formatters_by_ft = {
          lua = { 'stylua' },
          markdown = { 'deno_fmt', 'injected' },
        },
      }
    end,
  },
  -- add any other plugins here
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
-- add anything else here
```

**Comment by ribru17** [comment]
I made a PR for this if you would like to look, it isn't thoroughly tested though. Or if you think that the current behavior is desired I understand as well. Thanks!

**Comment by stevearc** [comment]
I added two PRs that fix this in different ways. Take a look and see if it works for you!

**Comment by ribru17** [comment]
Thanks so much! Personally I really like #118 but it's up to you :)

**Comment by stevearc** [comment]
Oh, I'm going to merge them both :)

**Comment by stevearc** [comment]
The `injected` formatter is still somewhat experimental and in early stages. I will definitely add more documentation as it settles into place. As for making `ignore_errors` the default, 

From "The Zen of Python"
> Errors should never pass silently.
> Unless explicitly silenced.

I really quite strongly agree with this one. I think it's worse to have something fail silently without your knowledge than to fail noisily in a way that is correctable. Of course, this would be better if the noisy failure also came with more instructions on how to fix it.

**Comment by chrisgrieser** [comment]
> Errors should never pass silently.

I fully agree, but the issue at hand is not about silent or verbose errors, but rather the fact that an error with one formats results in all formats falling, even though the formats should be able to work independent from each other.

**Comment by stevearc** [comment]
That is a good point, with potentially larger implications. If the formatters are intended to be independent, then maybe any time a formatter fails it should still continue to other formatters. This could be `prettier` + `injected`, or `isort` + `black`. I'll think about it some more, but I think I like that idea
