### ISSUE TITLE
[Question] Formatters are not detected

### ISSUE THREAD

**Issue by wojciech-kulik** [stevearc/conform.nvim#116]
Hello, 

here is my config:
```lua
return {
  "stevearc/conform.nvim",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    local conform = require('conform')

    conform.setup({
      forrmaters_by_ft = {
        swift = { "swiftformat" },
        lua = { "stylua" },
        markdown = { "prettier" },
        javascript = { "prettier" },
        html = { "prettier" },
        css = { "prettier" },
        yaml = { "prettier" },
        json = { "prettier" },
        -- Use the "*" filetype to run formatters on all filetypes.
        ["*"] = { "codespell" },
      },
      format_on_save = {
        timeout_ms = 500,
        lsp_fallback = true,
      },
      log_level = vim.log.levels.TRACE,
    })

    vim.keymap.set({ "n", "v" }, "<leader>mp", function()
      conform.format({
        lsp_fallback = true,
        async = false,
        timeout_ms = 500
      })
    end, { desc = "Format file or range (in visual mode)" })
  end
}
```
I installed all formatters via Homebrew, but it looks like formatters are not detected. When I open lua file and call `:ConformInfo` I get:
<img width="618" alt="image" src="https://github.com/stevearc/conform.nvim/assets/3128467/bbb8d0d0-8d12-4e62-8d0a-2818ce8d30f4">

When I open Swift file:
<img width="387" alt="image" src="https://github.com/stevearc/conform.nvim/assets/3128467/2b09ade9-8f31-4f3d-a358-92272f6110e2">

What do I do wrong?

**Comment by stevearc** [comment]
`forrmaters_by_ft` -> `formatters_by_ft`

**Comment by wojciech-kulik** [comment]
Hahaha 🤦 🤦 🤦  thank you for spotting it, I was fighting with it for over one hour and didn't notice that...
