### ISSUE TITLE
feature: lsp formatters per filetype

### ISSUE THREAD

**Issue by folke** [stevearc/conform.nvim#134]
Hi!

First of all thank you for this great plugin. I'm enjoying it quite a bit.

There currently is the option to use lsp as a fallback, but it's not possible to easily configure this per filetype.

Would be great if something like the below would be possible.

```lua
formatters_by_ft = {
  go = { "goimports", "lsp" }, -- runs goimports and all lsp formatters
},
```

```lua
formatters_by_ft = {
  go = { "goimports", "lsp:gopls" }, -- runs goimports and all only the gopls lsp formatter
},
```

**Comment by stevearc** [comment]
This kind of suggestion has been brought up before (#36, #61, #129), and I do like this API more, but the problem has always been that LSP formatters do not function like standalone formatters. The amount of complexity I would have to add to get that API is, I think, disproportionate to the benefit we would get.

While it's not quite as nice, you _can_ still control LSP formatting per-filetype relatively easily.

```lua
local extra_lang_args = {
  go = { lsp_fallback = "always", name = "gopls" },
}
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*",
  callback = function(args)
    local extra_args = extra_lang_args[vim.bo[args.buf].filetype] or {}
    require("conform").format(vim.tbl_deep_extend("keep", { bufnr = args.buf, lsp_fallback = true }, extra_args))
  end,
})
```

**Comment by folke** [comment]
yep, fair enough...

**Comment by pBorak** [comment]
@stevearc I think your suggestion may have a little issue with how you merge opts, shouldn't it be `force` instead of `keep` to use value from the rightmost map (extra_lang_args) ?

**Comment by stevearc** [comment]
@pBorak you're correct
