### ISSUE TITLE
feature: easier configuration

### ISSUE THREAD

**Issue by folke** [stevearc/conform.nvim#138]
**LazyVim** uses `conform.nvim` for formatting.

To make configuration easier, we added some extra options to `conform.nvim`:

- `opts.format`: default options used by `require("conform").format()`
- `opts.formatters`: instead of just adding new formatters, you can also override the default options for any formatter
- `opts.formatters[NAME].extra_args`: extra arguments passed to the formatter command.
  If you want to fully override the `args`, just use `args` instead of `extra_args`.

This all works as expected in LazyVim, but I believe these changes would benefit others as well.
Ideally, I also prefer not to deviate from a plugin's options.

Would you be open to accept a PR for this? If so I can create one.

# Example

```lua
{
  -- LazyVim will use these options when formatting with the conform.nvim formatter
  format = {
    timeout_ms = 1000,
  },
  formatters_by_ft = {
    lua = { "stylua" },
    fish = { "fish_indent" },
    sh = { "shfmt" },
  },
  -- LazyVim will merge the options you set here with builtin formatters.
  -- You can also define any custom formatters here.
  ---@type table<string,table>
  formatters = {
    injected = { options = { ignore_errors = true } },
    -- # Example of using dprint only when a dprint.json file is present
    dprint = {
      condition = function(ctx)
        return vim.fs.find({ "dprint.json" }, { path = ctx.filename, upward = true })[1]
      end,
    },
    --
    -- Example of using shfmt with extra args
    shfmt = {
      extra_args = { "-i", "2", "-ci" },
    },
  },
}
```

**Comment by stevearc** [comment]
I'm on board with the `opts.format` idea, though I'd prefer a more explicit name like `default_format_opts`.

I went back and forth on the formatter merging. I like that it's very simple right now; there's no magic you just set the values to what you want and they are used directly. But I do see the convenience value from merging the configs. I think it's worth trying out so I can get a feel for if this is intuitive or if it adds too much complexity. I've put up a PR with the initial implementation and will continue iterating on it this weekend

**Comment by folke** [comment]
Looks good!

**Comment by stevearc** [comment]
I've merged the config changes! Formatter configs get merged now and there's an easier way to add additional command line arguments.

I think I might backpedal on the other piece, though. While I think it makes sense for LazyVim to include a way to change the default options passed in to `conform.format()`, I don't know that it makes sense at the library level. Especially since it can change the default format mode from `sync` to `async`, it can make it difficult to tell what the behavior of `conform.format()` is going to be just by looking at the options passed in at the callsite.

**Comment by folke** [comment]
That's awesome, thanks!

And yes, makes sense not to include the defaults. User can for sure mess it up.

I think I'll just use the existing `format_on_save` options and unset them before setting up conform.

**Comment by gennaro-tedesco** [comment]
Is `extra_args` the current grammar to add extra arguments, or is it `prepend_args/args` as per the [docs](https://github.com/stevearc/conform.nvim#options)?

**Comment by stevearc** [comment]
@folke after some more thought on the shape of the config, I've ended up doing what you suggested in the beginning and added `default_format_opts` as a means of customizing the default behavior of `conform.format`. See #491 for the complete list of config changes

**Comment by folke** [comment]
Thank you for letting me know. Just updated LazyVim!
