### ISSUE TITLE
Not really a bug but how do you specify the code spacing? E.g. I want to format with 4 spaces instead of 2

### ISSUE THREAD

**Issue by Delice0** [stevearc/conform.nvim#141]
### Neovim version (nvim -v)

0.9.1

### Operating system/version

mac latest

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

N/A

### Describe the bug

N/A

### Steps To Reproduce

N/A

### Expected Behavior

I want to know how to change the spacing's

**Comment by stevearc** [comment]
That's entirely dependent on what formatter you're using. It's possible it can be configure via a config file, or by changing the arguments. Refer to [customizing formatters](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#customizing-formatters) or [Add extra arguments to a formatter command](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#add-extra-arguments-to-a-formatter-command) for how to change the command line arguments
