### ISSUE TITLE
question: disable autoformat of specific formatter

### ISSUE THREAD

**Issue by petobens** [stevearc/conform.nvim#148]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1377+g831d662ac6

### Operating system/version

Arch Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

-

### Describe the bug

Is it possible to disable autoformatting of a specific formatter? In markdown files I want to disable prettier autoformat but keep the trim_whitespace formatter. Using the config below both formatters get disabled:
```lua
conform.setup({
    formatters_by_ft = {
        markdown = { 'prettierd', 'trim_whitespace' },
    },
    format_on_save = function(bufnr)
        local ignore_filetypes = { 'markdown' }
        if vim.tbl_contains(ignore_filetypes, vim.bo[bufnr].filetype) then
            return
        end
        return { timeout_ms = 700, quiet = true, lsp_fallback = false }
    end,
})
```

### Steps To Reproduce

See above

### Expected Behavior

See above

### Minimal example file

-

**Comment by stevearc** [comment]
You can pass in an explicit list of formatters. So for example:

```lua
if vim.bo[bufnr].filetype == 'markdown' then
  return { timeout_ms = 700, quiet = true, lsp_fallback = false, formatters = { "trim_whitespace" } }
end

**Comment by petobens** [comment]
Thanks!
