### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jsekerez** [stevearc/conform.nvim#150]
### Neovim version (nvim -v)

0.9.4, Release

### Operating system/version

MacOS 14.0

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

          10:46:08[DEBUG] Running LSP formatter on /Users/[PRIVATE]/Rewards.tsx
          10:46:08[DEBUG] Running LSP formatter on /Users/[PRIVATE]/Rewards.tsx
          10:46:15[DEBUG] Running LSP formatter on /Users/[PRIVATE]/Rewards.tsx
          10:46:24[DEBUG] Running LSP formatter on /Users/[PRIVATE]/Rewards.tsx
          10:46:32[DEBUG] Running LSP formatter on /Users/[PRIVATE]/Rewards.tsx

### Describe the bug

When formatting, either before or after save, with either prettier or black (I haven't tried with other formatters), text from some lines is cut out for half a second - in the example, see the line under the cursor, as well as the last line.

### Steps To Reproduce

1. Open a formatted file
2. On one line, introduce changes that the formatter will amend
3. Save

### Expected Behavior

The lines shouldn't blank out.

### Minimal example file

```typescript
  return (
    <Card className={classes.card}>
      <Box py={3} px={2}>
        <Box display="flex" justifyContent="space-between">
          <Typography variant="overline">{name}</Typography>
          <Box display="flex">
            <Star className={classes.star} />
            <Star className={classes.star} />
            <Star className={classes.star} />
            <Star className={classes.star} />
            <Star className={classes.star} />
          </Box>
        </Box>
        <Typography variant="subtitle2">"{review}"</Typography>
      </Box>
    </Card>
  );
};

const BBBReviews = () => {
  const classes = useStyles();
  const theme = useTheme();
  const isMedScreen = useMediaQuery(theme.breakpoints.down("md"));
  const isMobile = useMediaQuery(theme.breakpoints.down("xs"));

  let containerPadding = isMobile ? 2 : 3;

  return (
    <>
      <Box mb={1}>
        <Typography variant="subtitle2">
          See what other borrowers are saying about us

```

### Minimal init.lua

```Lua
{
    "stevearc/conform.nvim",
    event = { "BufWritePre" },
    cmd = { "ConformInfo" },
    opts = {
      formatters_by_ft = {
        lua = { "stylua" },
        python = { "black" },
        javascript = { "prettier" },
        yaml = { "yamlfix" },
        json = { "fixjson" },
        zig = { "zigfmt" },
      },
      format_on_save = function(bufnr)
        if slow_format_filetypes[vim.bo[bufnr].filetype] then return end
        local function on_format(err)
          if err and err:match "timeout$" then slow_format_filetypes[vim.bo[bufnr].filetype] = true end
        end

        return { timeout_ms = 200, lsp_fallback = true }, on_format
      end,

      format_after_save = function(bufnr)
        if not slow_format_filetypes[vim.bo[bufnr].filetype] then return end
        return { lsp_fallback = true }
      end,
      log_level = vim.log.levels.DEBUG,
    },
  },
```

### Additional context

https://github.com/stevearc/conform.nvim/assets/102981194/6d36a480-8a4a-4cb8-ae1e-91df8d417b1a

**Comment by stevearc** [comment]
Just from looking at this, I'm like 90% sure that this is an interaction between the LSP applied formatting and indent-blankline. LSP formatting preserves extmarks, and indent-blankline uses extmarks to draw the guides. If the formatter moves text to the left and keeps the previous marks, I would believe that they could temporarily overwrite the actual text until indent-blankline picks up on the changes and redraws.

First thing I would recommend is disable indent-blankline and see if the issue repros. If it doesn't, then my assessment is likely at least somewhat correct. In that case, I'd recommend posting on the indent-blankline repo and ask for recommendations. One thing that might work is if there's a way to manually trigger the redraw. Conform provides a callback for when formatting completes, so if you could trigger the redraw in that callback it might not have that visual delay.
