### ISSUE TITLE
bug: Conform does not respec ignored files for the formatter

### ISSUE THREAD

**Issue by leoncruz** [stevearc/conform.nvim#154]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: ~/.local/state/nvim/conform.log
          14:14:59[WARN] Formatter 'rubocop' was interrupted
          14:32:32[WARN] Formatter 'rubocop' was interrupted
          14:39:33[WARN] Formatter 'rubocop' was interrupted
          14:45:05[WARN] Formatter 'rubocop' was interrupted
          14:56:50[WARN] Formatter 'rubocop' was interrupted
          10:07:29[WARN] Formatter 'rubocop' was interrupted
          13:06:19[WARN] Delayed Neovim exit by 508ms to wait for formatting to complete
          13:06:19[ERROR] Formatter 'rubocop' error: nil
          14:12:08[WARN] Formatter 'rubocop' was interrupted
          14:12:49[WARN] Formatter 'rubocop' was interrupted
          16:40:42[WARN] Formatter 'rubocop' was interrupted
          16:42:10[WARN] Formatter 'rubocop' was interrupted
          17:15:32[WARN] Formatter 'rubocop' was interrupted
          23:18:00[WARN] Formatter 'rubocop' was interrupted
          17:37:13[WARN] Formatter 'rubocop' was interrupted
          16:40:45[WARN] Formatter 'rubocop' was interrupted
          17:15:31[WARN] Formatter 'rubocop' was interrupted
          01:11:56[ERROR] Formatter 'prettier' error: [error] Invalid semi value. Expected true or false, but received "false".

Formatters for this buffer:
LSP: solargraph
rubocop ready (ruby)

Other formatters:
prettier ready (typescriptreact, javascriptreact, typescript, javascript)

### Describe the bug

Conform is formatting ruby files with rubocop even if this files are marked to be ignored. I have tested with eslint and javascript and the same happend. For the rubocop I setup de ignore files on .rubocop.yml file. The lint does not work for this files, as expected, but the Conform format the file. If run the command `rubocop -a`, the format does not happend. The same for the eslint and javascript

### Steps To Reproduce

1. Create a project with ruby or javascript
2. Install rubocop (for ruby) or eslint (for javascript)
3. Mark a file as ignored
4. Write some code that ofenses the formatter and save

### Expected Behavior

Should does not format the ignored files

### Additional context

this is my conform.nvim setup: 
```lua
return {
	'stevearc/conform.nvim',
	config = function()
		require('conform').setup({
			formatters_by_ft = {
				ruby = { 'rubocop' },
				javascript = { 'prettier' },
				typescript = { 'prettier' },
				javascriptreact = { 'prettier' },
				typescriptreact = { 'prettier' },
			},
			format_after_save = {
				lsp_fallback = true,
				timeout_ms = 500,
			}
		})
	end
}
```

**Comment by stevearc** [comment]
Unfortunately conform does not integrate with specific formatters to detect if they are in a configured ignorelist or not. I would consider accepting something like that as a pull request, but a big barrier is that Neovim doesn't have any convenient library for parsing yaml files. At the moment, this is simply out of scope.

You can of course use a function for `format_after_save` and try to do your own detection for whether the formatter should be run or not. Solving this for your specific case via some hacks will be much easier than solving this in the general case with yaml parsing.
