### ISSUE TITLE
Feature request: auto discovery

### ISSUE THREAD

**Issue by Zeioth** [stevearc/conform.nvim#163]
### Neovim version (nvim -v)

x

### Operating system/version

x

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

x

## Currently
One have to do 

```lua
formatters_by_ft = {
  javascript = { "prettier" }
},
```
Which requires interaction from the user.

## Proposal
* Auto discover and enable all formatters installed by mason by default.
* `formatters_by_ft` remain as a way to override/disable the formaters used for a given ft.

## Advantages
* No need for manual configuration. Confort.nvim works out of the box.

### Steps To Reproduce

x

### Expected Behavior

x

### Minimal example file

x

### Minimal init.lua

```Lua
x
```

### Additional context

x

**Comment by stevearc** [comment]
There isn't really a good way to resolve conflicts for formatters that can handle the same filetypes. Should we run just one of them? All of them? What order? We could make it do _something_ with the mason formatters for sure, but in a good percentage of cases I expect the behavior will be surprising and undesired. That make it unsuitable as a default. I much prefer keeping the conform configuration very explicit. It makes it very easy to tell what the plugin is doing just from looking at the one setup function (which in turn helps me debug issues that people report).

**Comment by Zeioth** [comment]
The behavior null-ls had in this scenario was to load all formatters installed by mason for the current filetype. It makes sense: Why would you install a formatter if you are not gonna use it?

But I get it, it's a tricky thing.
