### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [stevearc/conform.nvim#166]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/stevearc/conform.nvim/assets/147402107/39ed14dd-9c06-4599-9c54-719cd1d8b509)

**Comment by Kalyanimhala** [comment]
@stevearc  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by stevearc** [comment]
Github already displays contributors in a section of the repo home page. This section makes some sense in a README when there are contributions from people that won't show up there (wiki changes, translations, designs), but this project doesn't have any of those.
