### ISSUE TITLE
`erb_format` configuration missing

### ISSUE THREAD

**Issue by mustafaergul** [stevearc/conform.nvim#168]
Thank you for the tool! Enjoying so far. However, I think there needs to be more documentation on how the erb_format config should look.

Could you give some some snipped config how formatted and filetype are defined. Currently tried the config below and didn't work so far;

local conform = require("conform")

```
conform.setup({
	formatters_by_ft = {
		lua = { "stylua" },
		ruby = { "standardrb" },
		erb_format = { "erb-format" },
	},
 ...
```

**Comment by stevearc** [comment]
The keys of the `formatters_by_ft` table should be filetypes. The filetype of an ERB file should be `erb`, so the following should work:

```lua
conform.setup({
	formatters_by_ft = {
		lua = { "stylua" },
		ruby = { "standardrb" },
		erb = { "erb-format" },
	},
})
```

**Comment by a-chacon** [comment]
I know this is closed. But I can't make it works with `erb` filetype. It works with `eruby`. I leave this here if someone more is having this problem.

**Comment by tymoyato** [comment]
> I know this is closed. But I can't make it works with `erb` filetype. It works with `eruby`. I leave this here if someone more is having this problem.

I'm getting error about "No config found" -> M.get_formatter_info = function(formatter, bufnr)

https://github.com/stevearc/conform.nvim/blob/a6965ac128eba75537ec2bc5ddd5d5e357062bdc/lua/conform/init.lua#L626

I'm currently trying to find a solution

**Comment by tymoyato** [comment]
> I know this is closed. But I can't make it works with `erb` filetype. It works with `eruby`. I leave this here if someone more is having this problem.

try this config 
```lua
conform.setup({
	formatters_by_ft = {
		lua = { "stylua" },
		ruby = { "standardrb" },
		eruby = { "erb_format" },
	},
})
```

It works on erb files I just did it.

**Comment by tymoyato** [comment]
> Yes! I was answering that when you remove the last comment hehe Good! That was I said with: `It works with eruby`

Thanks you !
