### ISSUE TITLE
enhancement: multi step/command formatting

### ISSUE THREAD

**Issue by RingOfStorms** [stevearc/conform.nvim#169]
For some languages I run multiple different formatting tools in sequence to achieve the formatting end result I desire. It would be great if conform had some pattern for running multiple commands. As it is now it seems like the only way to achieve this would be through some custom command that pipes formatters together.

In null-ls, for example, it runs all formatters in order if they apply to the file. So I was able to write this:
https://github.com/RingOfStorms/nvim/blob/master/lua/plugins/null-ls.lua#L74-L75

and get formatting from two commands.

**Comment by stevearc** [comment]
This is supported. If you look at the code in the [setup section](https://github.com/stevearc/conform.nvim#setup) you'll see an example for python that runs `isort` and then `black`
