### ISSUE TITLE
Feature request: return all formatters in sublist for list_formatters

### ISSUE THREAD

**Issue by MoritzBoehme** [stevearc/conform.nvim#172]
The problem I'm facing is that some formatters are rather opinionated, and I cannot always use them on all projects I'm contributing on.
Right now I have `conform` configured such that the more tame formatter is used first and only if it is not present I use the opinionated formatter. This of course means I will always just use the first formatter.

Example config:
```lua
require("conform").setup({
  formatters_by_ft = {
    python = { { "isort", "black" } },
  },
})
```

Now I was just trying to add a simple user command which lets me choose a subset of formatters to apply to the current buffer manually:
```lua
local conform = require("conform")

vim.api.nvim_create_user_command("Format", function(opts)
  local formatters = vim.split(opts.args, "%s+", { trimempty = true })
  conform.format({ formatters = formatters })
end, {
  nargs = "+",
  complete = function()
    local formatter_name = function(formatter_info)
      return formatter_info.name
    end
    return vim.tbl_map(formatter_name, conform.list_formatters())
  end,
})
```

However, I noticed that in this case, `list_formatters` only returns the first formatter.

Having explained all this, does anybody (maybe more experienced with lua) have an idea on how to implement my use case?
My proposal would be to either add a function which returns all configured formatters, even if superseded by another, or add a flag to `list_formatters` to get this behavior or something alike.

PS: Thanks for the nice plugin @stevearc. It's by far the best formatting plugin I have had the pleasure to use to date.

**Comment by stevearc** [comment]
Looking at your use case, the best suggestion I have for you is to treat conform like an imperative API instead of a framework you have to fit into. At the end of the day, `formatters_by_ft` and `format_on_save` are both just effectively "helper functions" that you can easily replicate yourself. Try something like this:

```lua
local conform = require("conform")

local formatters_by_ft = {
  python = { "isort", "black" },
}

conform.setup({
  format_on_save = { lsp_fallback = true },
})
for ft, formatters in pairs(formatters_by_ft) do
  -- Wrap each of the formatter lists so we only use the first
  conform.formatters_by_ft[ft] = { formatters }
end

vim.api.nvim_create_user_command("Format", function(opts)
  conform.format({ formatters = opts.fargs })
end, {
  nargs = "+",
  complete = function()
    local names = formatters_by_ft[vim.bo.filetype] or {}
    local formatters = vim.tbl_map(conform.get_formatter_info, names)
    formatters = vim.tbl_filter(function(formatter)
      return formatter.available
    end, formatters)
    return vim.tbl_map(function(formatter_info)
      return formatter_info.name
    end, formatters)
  end,
})
```

**Comment by MoritzBoehme** [comment]
Thanks, that's a great starting point. I hadn't thought about it like this...
