### ISSUE TITLE
bug: neovim exits with code 134 when running `:wq`

### ISSUE THREAD

**Issue by debugloop** [stevearc/conform.nvim#173]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

NixOS

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

```
10:34:33[DEBUG] Running formatters on /home/danieln/test.lua: { "stylua" }
10:34:33[INFO] Run stylua on /home/danieln/test.lua
10:34:33[DEBUG] Run command: { "stylua", "--search-parent-directories", "--stdin-filepath", "/home/danieln/test.lua", "-" }
10:34:33[DEBUG] stylua exited with code 0
```

### Describe the bug

Nvim sometimes exits with code 134 instead of 0. Sometimes is kind of vague really, but it rarely occurs during real editing. However, with a small test file such as editing the `repro.lua` using itself, it occurs nearly every time for me. During exit, a line flashes on the command line when using my config (not the `repro.lua`, I use noice.nvim which causes the line to flash, I think)

```
nvim: src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
```
(typed off a screenrecording frame, it clears instantly...)

### Steps To Reproduce

1. `nvim -u repro.lua repro.lua`
2. `:wq`
3. observe code 134, nearly every time

### Expected Behavior

Regular exit.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
        formatters_by_ft = {
          lua = { "stylua" },
        },
        format_on_save = {
          lsp_fallback = true,
          timeout_ms = 5000,
        },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I think I've narrowed this down to a bug in Neovim (introduced in v0.9.0). Could you try out the attached PR and see if it fixes the problem for you?

**Comment by debugloop** [comment]
Tested with a quick for loop in 200 iterations: Seems to work just fine 🚀 If it is any help at all, in the mean time I found and used this work around:

```lua
-- HACK: This shifty 1ms delay prevents a libuv error and nvim exiting with code 134 on `:wq`.
vim.api.nvim_create_autocmd({ "VimLeave" }, {
  callback = function()
    vim.cmd("sleep 1m")
  end,
})
```

Thanks for the quick help 👍🏻
