### ISSUE TITLE
Question: how to configure run formatters `a` or both (`b` + `c`) ?

### ISSUE THREAD

**Issue by linrongbin16** [stevearc/conform.nvim#174]
Hi, thanks for your plugin, I have 1 question:

I want to configure formatting python with either `ruff`, or both `isort` and `black`.

How should I configure it with `formatters_by_ft` option?

Since it looks for now it only support:

1. running all formatters in a list: `python = { "isort", "black" }`.
2. running one of the formatters and skip others in a sub list: `python = { {"ruff", "black"} }`.

But I want something that running one of the groups and skip others, the `group` is either the `ruff`, or the `{ "isort", "black" }`.

Will `python = { { "ruff", { "isort", "black" } } }` do the work???

**Comment by linrongbin16** [comment]
Update:

The `python = { { "ruff", { "isort", "black" } } }` is not working:

<img width="1377" alt="image" src="https://github.com/stevearc/conform.nvim/assets/6496887/70ba336f-06f4-4e40-a2fa-96b09513e2fc">

**Comment by MoritzBoehme** [comment]
As far as I can see, ruff is split into two parts `ruff_format` and `ruff_fix` in this [repo](https://github.com/stevearc/conform.nvim#formatters). 
So you could add something like `python = { { "ruff_fix", "isort" } , { "ruff_format", "black" } }`.

Note that we first run `ruff_fix` and then `ruff_format` because the fix can be to delete unneeded imports, which affects the formatting.

**Comment by mehalter** [comment]
That is a great work around for the case of `ruff` but not all formatters will be as nicely laid out. I think it is a good idea to be able to support the original request as well

**Comment by linrongbin16** [comment]
@mehalter , yeah, the idea is:

1. the (`python`) list contains multiple items, and try running each item in the list, if one of them successfully format the code, then stop. Thus only the first installed formatters would success.
2. Each item is either:
   1. A plain string, e.g., the formatter name.
   2. A lua list contains multiple plain strings, that each of them is a formatter name (the `isort`, `black`), thus all of the formatters in this list need to run.

**Comment by stevearc** [comment]
When I was initially designing the structure of the `formatters_by_ft` option I actually thought of this use case, but couldn't come up with a way to support it that was simple enough for my liking. The official stance is that if you want more complex behavior you can make it yourself using the API. For example:

```lua
local conform = require("conform")
conform.setup({
  format_on_save = function(bufnr)
    if vim.bo[bufnr].filetype == "python" then
      if conform.get_formatter_info("ruff_format", bufnr).available then
        return { formatters = { "ruff_format" } }
      else
        return { formatters = { "isort", "black" } }
      end
    end
    return { lsp_fallback = true }
  end,
})
```

However I do see that it's a bit awkward if you want to synchronize the default formatters used in `format_on_save` and `conform.format()`. What do you think of extending `formatters_by_ft` to allow for it to be a function that returns a list of formatters? Something like

```lua
local conform = require("conform")
conform.setup({
  formatters_by_ft = {
    python = function(bufnr)
      if conform.get_formatter_info("ruff_format", bufnr).available then
        return { "ruff_format" }
      else
        return { "isort", "black" }
      end
    end,
  },
})
```

**Comment by mehalter** [comment]
Right now the current syntax for the formatter list basically follows:

```
Sequence = (Formatter|Options)[]
Options = Formatter[]
Formatter = string
```

It could follow a relatively simple recursive structure:

```
Sequence = Formatter|(Formatter|Options)[]
Options = Sequence[]
Formatter = string
```

I believe this context free grammar like definition would be able to correctly parse in a general sense an interpretation of the original request while also adding the ability to specify a single formatter as just a string an recursively define more choices:

```lua
{
  formatters_by_ft = {
    python = { { "ruff", { "isort", "black" } } },
    javascript = { { "prettierd", "prettier" } },
    sh = "shfmt",
    ["_"] = { "trim_newlines", "trim_whitespace" }
  },
}
```

Even if this is implemented in this way, I do think it's a good idea to also add that function notation for arbitrary extension as well!

**Comment by mehalter** [comment]
This representation is basically a flat encoding of a tree like data structure where each path from the root to a leaf is a different pipeline of formatters with an inherent priority for the preferred path down the tree. This sounds pretty ideal for a representation that matches the methodology of conform while also allowing for efficient calculation of the first, most preferred path that all the formatters are available for.

This also wouldn't be a breaking change on the current syntax since the original syntax still parses the same with the new grammar. It's would simply just extend on top of it.

**Comment by stevearc** [comment]
@mehalter the thing I don't like about this nesting is that it becomes incredibly unclear when a list means "take the first" and when a list means "run all in sequence". I think that extending the config to support this would make things less clear than just using a function to define your logic. When I look at
`python = { { "ruff", { "isort", { "black", "pep8" } } } }`
there are so many different ways this could be interpreted, and I don't want to deal with that ambiguity.

**Comment by mehalter** [comment]
Yeah I totally agree @stevearc

**Comment by stevearc** [comment]
Added function support. Documented in `:help conform-options`

**Comment by mehalter** [comment]
Out of curiosity @stevearc how often is that function resolved? Is it just once when the buffer is opened or is it every time the format function is called?

**Comment by stevearc** [comment]
It will be run every time the format function is called

**Comment by mehalter** [comment]
Awesome! That's what I was hoping for as well. Thanks for your work on this!
