### ISSUE TITLE
bug: trim trailspace even in gitcommit files

### ISSUE THREAD

**Issue by sandangel** [stevearc/conform.nvim#185]
### Neovim version (nvim -v)

nightly

### Operating system/version

linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

N/A

### Describe the bug

Hi, I realize that this formatter will also trim trailing space. That is perfectly fine, but how can I disable that behavior with gitcommit files? because the trailing space has special meaning in that file.

### Steps To Reproduce

1. set nvim as your git commit editor
2. in your project, run `git add .` , `git commit`
3. In your nvim, write the commit message
4. Check the content of the diff below the commit message, there are some diff with trailing white space.
5. save the commit message, then the trailing whitespace is removed.

### Expected Behavior

Should be able to configure not trimming the trailing whitespace in some filetypes.

### Minimal example file

N/A

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by gegoune** [comment]
I do something like that:

```lua
local disabled_filetypes = { 'mail', 'gitcommit', 'gitrebase', 'lua', 'python' }

require('conform.formatters.trim_whitespace').condition = function(ctx)
  return not vim.tbl_contains(disabled_filetypes, vim.bo[ctx.buf].filetype)
end
```

**Comment by sandangel** [comment]
are you doing that before the setup call or after?
This config does not work for me:

```lua
  {
    'stevearc/conform.nvim',
    event = 'VeryLazy',
    opts = {
      format_on_save = {
        lsp_fallback = true,
      },
    },
    config = function(_, opts)
      require('conform').setup(opts)
      local disabled_filetypes = { 'gitcommit', 'gitrebase', 'diff' }
      require('conform.formatters.trim_whitespace').condition = function(ctx)
        return not vim.tbl_contains(disabled_filetypes, vim.bo[ctx.buf].filetype)
      end
    end
  },
```

**Comment by gegoune** [comment]
I do that before calling `setup()` although not sure if it makes a difference or not.

**Comment by sandangel** [comment]
Still, does not work for me in both cases.

**Comment by gegoune** [comment]
Not sure why, works for me, sorry. I don't use lazy nor do any lazy loading; maybe that's where issue is.

**Comment by sandangel** [comment]
Hmm, i tried disabling this plugin but problem still exist. Could be because of lspconfig. Let me try. Thanks for helping me
