### ISSUE TITLE
Feature request: Support using lua function as formatter

### ISSUE THREAD

**Issue by nghialm269** [stevearc/conform.nvim#186]
Hi, thanks for the plugin, I'm planning to migrate over from null-ls.

I'm wondering if it's possible to use lua function as formatter, instead of command?

My use case is like this:
1. I want to create an `lsp` formatter instead of relying on the `lsp_fallback` option. This way I can control the order and filetypes of the lsp formatter like other formatters.
2. I want to create an `lsp_goimport` formatter that uses the `organizeImport` code action from `gopls`. In my experience it's faster than executing the `goimports` binary (maybe because `gopls` already has the file content in memory?).

Something like this:
```lua
{
  formatters_by_ft = {
    lua = { "stylua" },
    -- Conform will run multiple formatters sequentially
    go = { "lsp", "lsp_goimports" },
  },
  formatters = {
    lsp = { luafunc= require('conform.lsp_format').format },
    lsp_goimport = { luafunc = function() --[[ execute lsp organizeImport code action ]] end },
  },
}
```

**Comment by stevearc** [comment]
There _is_ a way to use a lua function as a formatter; this is how the `injected` formatter works:
https://github.com/stevearc/conform.nvim/blob/161d95bfbb1ad1a2b89ba2ea75ca1b5e012a111e/lua/conform/formatters/injected.lua#L66-L80

However, a word of warning for this use case: there is a fundamental disconnect between how LSP does formatting and code actions and how all other formatters behave. This is why there is no `"lsp"` formatter. The LSP operations are performed _directly_ on the buffer, whereas other formatters can run in a stateless manner without directly making changes. You may be able to get something that works most of the time, but just be aware that this is a direction that is explicitly not supported and you should expect weird behavior and frustration.

I go into this topic in more detail in #61
