### ISSUE TITLE
bug:  `async` format after buffer changes only fires after saving twice

### ISSUE THREAD

**Issue by rawhat** [stevearc/conform.nvim#19]
### Neovim version (nvim -v)

v0.10.0-dev-997+g6463116818

### Operating system/version

Arch Linux WSL2

### Output of :ConformInfo

```
Log file: /home/alex/.local/state/nvim/conform.log

Formatters for this buffer:
stylua ready (lua)

Other formatters:
```

### Describe the bug

If I open a buffer with some text that needs formatting and save, it's correctly formatted.

If I make a change, say like indent something, and then save, it doesn't format.  If I save _again_, it does format.

When not using async, it blocks and formats no problem on the first save.

### Steps To Reproduce

Using this in a `lazy.nvim` config.  The only other plugins I am using for this are `catppuccin` and `nvim-treesitter`, which I don't expect to interfere with it.  I can remove those and re-try if you think otherwise!

```lua
{
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        formatters_by_ft = {
          lua = { "stylua" },
        },
      })
      vim.api.nvim_create_autocmd("BufWritePre", {
        pattern = "*",
        callback = function(args)
          require("conform").format({ async = true, lsp_fallback = true, buf = args.buf })
        end,
      })
    end,
}
```

Then I open my `init.lua` and indent something.  Press `:w`, no format.  Then I `:q` and reopen the file.  `:w` will then correctly format. If I indent again, then press `:w` and then `:w` again, it formats.

### Expected Behavior

It should format on the first save.

### Minimal init.lua

(Just removing this since what I have above is pretty much it.  It's the same lazy setup as the one in the template. Can provide the full file if that's preferred).

**Comment by stevearc** [comment]
What's happening is the async formatter will discard its results if the buffer has changed in between when you called `format()` and when the formatter returns its results. You will see log lines to this effect in `:ConformInfo` if you set `log_level = vim.log.levels.INFO`.

From `:help changedtick`:
```
b:changedtick	The total number of changes to the current buffer.  It is
		incremented for each change.  An undo command is also a change
		in this case.  Resetting 'modified' when writing the buffer is
		also counted.
```
The issue here is that this command runs in `BufWritePre`, then after the autocmd vim will write the file and set `modified = false` on the buffer, which increments the `changedtick`.

In general, I would recommend synchronous formatting on save. For fast formatters like `stylua` it should complete almost instantaneously. Additionally, async formatting effectively means you have to save twice. Once to trigger the format, and again with the formatted content.

If you're attached to the idea of asynchronous formatting on save, you can set `modified = false` before you call `format()` and that will prevent the changedtick from updating mid-flight.

```lua
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*",
  callback = function(args)
    vim.bo[args.buf].modified = false
    require("conform").format({ async = true, lsp_fallback = true, buf = args.buf })
  end,
})
```

**Comment by stevearc** [comment]
Small correction to my last suggestion: it would be better to do the formatting in `BufWritePost` than to hack the `modified` status.

```lua
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = "*",
  callback = function(args)
    require("conform").format({ async = true, lsp_fallback = true, buf = args.buf })
  end,
})
```

It would then be reasonable to want a way to save the buffer once the formatting completes. I will provide a mechanism for that shortly

**Comment by rawhat** [comment]
Awesome, thank you for all the info!  To be honest, I'm more than happy with synchronous formatting, for most things it's fast enough.  Up to you if you think that functionality is worth adding.

I was hoping to synchronously format on `:wq`, but asynchronously format for most other things.  I suspect that won't really work the way I want, so maybe I'll just stick with synchronous.

Thanks again :)

**Comment by stevearc** [comment]
I put up a PR that will add a callback argument to `format()`. It's code complete but I need to do some testing and maybe add some tests. I'm unfortunately out of time for today, so I'll try to finish it up tomorrow.

With this, it should be possible to do the following:
```lua
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = "*",
  callback = function(args)
    require("conform").format({ async = true, lsp_fallback = true, buf = args.buf }, function(err)
      if not err then
        vim.api.nvim_buf_call(args.buf, function()
          vim.cmd.update()
        end)
      end
    end)
  end,
})
```
