### ISSUE TITLE
Question: How do you configure a custom formatter?

### ISSUE THREAD

**Issue by Delice0** [stevearc/conform.nvim#197]
### Neovim version (nvim -v)

latest

### Operating system/version

latest

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

n/a

### Describe the bug

I have a checkstyle xml file that has some predefined configuration for formatting in my java project and I would like to use this file inside my java project.

How do I that?

### Steps To Reproduce

n/a

### Expected Behavior

n/a

### Minimal example file

n/a

### Minimal init.lua

```Lua
n/a
```

### Additional context

n/a

**Comment by stevearc** [comment]
If you look at the `formatters` key in the [options documentation](https://github.com/stevearc/conform.nvim#options) it describes the layout of a custom formatter. At a minimum you will need a `command` that is run, possibly with some `args` as well. If the command accepts stdin and prints the formatted results to stdout, then you're done. If not, you'll want to set `stdin = false`.

**Comment by conradogarciaberrotaran** [comment]
Hi, sorry to revive this. How can I make the command call something installed by Mason?

Thanks!
