### ISSUE TITLE
Run injected language formatters with lsp

### ISSUE THREAD

**Issue by zoriya** [stevearc/conform.nvim#200]
I want to format the main file with the lsp (if it supports it) but also format each injected blocks with the formatter specified in conform.
Currently, if we specify:
```lua
{
	formatters_by_ft = {
		["*"] = { "injected" }
	}
}
```
it disables lsp formatting.

**Comment by thenbe** [comment]
Not sure if just a typo in your text snippet, but the formatter's name is [`injected`](https://github.com/stevearc/conform.nvim/blob/4524a687107c6e598017dc7356b7cd1eb046aa71/doc/conform.txt#L233) (not `inject`).

**Comment by zoriya** [comment]
Sorry, that's a typo

**Comment by stevearc** [comment]
This is why you can also pass `lsp_fallback = "always"`. If you only want that to happen for certain filetypes, you can add any custom logic to the format_on_save function

**Comment by stevearc** [comment]
So by default if you pass `lsp_fallback = true` then if there are _no_ formatters or if the formatters for the filetype are only from the `"_"` and `"*"` filetypes, formatting will fall back to LSP. I believe this is your use case. You can verify this by opening a file that you want to format and running `:=require("conform").will_fallback_lsp()`

**Comment by zoriya** [comment]
Right now with `lsp_fallback = true`, the `"*"` formatter is not run. I want to run both the `"*"` formatter and the lsp. I can do that by using `lsp_fallback = "always"` but doing so makes the lsp formatter run even when i have something like `js = "prettier"` which I don't want.

**Comment by stevearc** [comment]
This use case exceeds the bounds of what the simple config options support. I'd recommend calling `conform.format` directly with the desired list of formatters, setting `lsp_fallback = "always"` when you want LSP formatting to be applied at the end

**Comment by zoriya** [comment]
Coming back to this due to the notification, but having a formatter named `lsp` instead of a config key `lsp_fallback` would solve this issue since you could do:

```lua
{
	formatters_by_ft = {
		["_"] = { "injected", "lsp" },
		["*"] = { "injected" },
	}
}
```

**Comment by pandanoir** [comment]
Is this issue resolved by https://github.com/stevearc/conform.nvim/pull/491 ?

**Comment by zoriya** [comment]
It doesn't because "_" and "*" does not support setting lsp_fallback.

**Comment by mehalter** [comment]
@zoriya I have stumbled across wanting this as well and just wanted to drop the solution I am using currently in my configuration that seems to work great:

```lua
formatters_by_ft = {
  ["*"] = { "injected" }, -- always add injected even if filetype adds other formatters
  ["_"] = { "injected", lsp_format = "last" }, -- fallback to injected where running lsp last
  -- add other filetype specific formatters that will not necessarily use lsp
}
```

**Comment by JeanMertz** [comment]
Just adding a "me too" here. I ran into this, and it took me a while to figure out what was happening here. I'm in the same boat as @zoriya as I want to run the LSP fallback _even_ if I have `injected` enabled.

I don't know why, but @mehalter's proposed solution did not work for me. To be clear, I do not specify every filetype in `formatters_by_ft`, but they still trigger in `format_on_save`.

For now I'm adding custom logic to `format_on_save` to explicitly set `always` for filetypes that always need to run, regardless of other active formatters.

**Comment by gshpychka** [comment]
Can this be reopened (or closed as "Not planned")? @stevearc
