### ISSUE TITLE
bug: How to add Packer formatter (getting "No config found")

### ISSUE THREAD

**Issue by mpas** [stevearc/conform.nvim#201]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 13.6

### Describe the bug

Have added the following formatter for usage with packer. Normally this runs like

`packer fmt .` # using the current directory
`packer fmt --recursive .` # using the current directory and then recursive.

```
    formatters = {
      packer_fmt = {
        command = "packer",
        args = { "fmt", "." },
        stdin = false,
      },
    },
    opts = {
      formatters_by_ft = {
        sh = { "shfmt" },
        hcl = { "packer_fmt" },
      },
    },
```

When I save a file `ConformInfo` gives a message:
```
Formatters for this buffer:
packer_fmt unavailable: No config found
```

I am missing something to achieve running packer as formatter?

**Comment by lbiaggi** [comment]
Have you tried to expand the `.` with `vim.fn.expand('%:p')`?

**Comment by mpas** [comment]
> vim.fn.expand('%:p')

Not a Lua guru :)

But tried this giving the same result.

```
    formatters = {
      packer_fmt = {
        command = "packer",
        args = { "fmt", vim.fn.expand("%:p") },
        stdin = false,
      },
    },
    opts = {
      formatters_by_ft = {
        sh = { "shfmt" },
        hcl = { "packer_fmt" },
      },
    },

```
