### ISSUE TITLE
bug: prettierd range formatting not working on markdown file

### ISSUE THREAD

**Issue by petobens** [stevearc/conform.nvim#203]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1573+gd92dd2a0c0

### Operating system/version

Arch Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

```
18:58:45[DEBUG] Running formatters on /home/pedro/Desktop/foo.md: { "prettierd", "injected" }
18:58:45[INFO] Run prettierd on /home/pedro/Desktop/foo.md
18:58:45[DEBUG] Run command: { "prettierd", "/home/pedro/Desktop/foo.md" }
18:58:45[DEBUG] Run CWD: /home/pedro
18:58:45[DEBUG] prettierd exited with code 0
18:58:45[INFO] Run injected on /home/pedro/Desktop/foo.md
18:58:48[DEBUG] Running formatters on /home/pedro/Desktop/foo.md: { "prettierd", "injected" }
18:58:48[INFO] Run prettierd on /home/pedro/Desktop/foo.md
18:58:48[DEBUG] Run command: { "prettierd", "/home/pedro/Desktop/foo.md", "--range-start=11", "--range-end=40" }
18:58:48[DEBUG] Run CWD: /home/pedro
18:58:48[DEBUG] prettierd exited with code 0
18:58:48[INFO] Run injected on /home/pedro/Desktop/foo.md
```

### Describe the bug

Prettierd range formatting doesn't seem to work on a markdown file.

### Steps To Reproduce

1. Open nvim with the minimal provided init.lua
2. Edit the minimal example file `foo.md`
3. Press `,fc` to format the code -> ordered number list are correctly formatted
4. Press `u` to undo the change
5. Selected the ordered list and press `,fc`

### Expected Behavior

After 5. the list should get formatted/ordered (the last item `3.` should be replaced by a `4.`)

### Minimal example file

```md
# H1

Foo

1. one
2. two
3. three
3. four

Bar
```

### Minimal init.lua

```Lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        config = function()
            require('nvim-treesitter.configs').setup({
                ensure_installed = {
                    'markdown',
                    'markdown_inline',
                },
            })
        end,
    },
    {
        'stevearc/conform.nvim',
        config = function()
            local conform = require('conform')
            conform.setup({
                formatters_by_ft = {
                    markdown = { 'prettierd', 'injected' },
                },
                notify_on_error = true,
                log_level = vim.log.levels.DEBUG,
            })

            vim.keymap.set({ 'n', 'v' }, ',fc', function()
                conform.format({ async = true, lsp_fallback = false })
            end)
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

### Additional context

![conformprettier](https://github.com/stevearc/conform.nvim/assets/2583971/32ffd51c-a260-4145-8038-7dc15f1bdaa0)

**Comment by stevearc** [comment]
You can try setting `log_level = vim.log.levels.TRACE` to see even more detailed information about the formatting.

If you run `prettierd /home/pedro/Desktop/foo.md --range-start=11 --range-end=40`, what do you see? Can you construct any `prettierd` command with range arguments that produces the output you expect?

**Comment by petobens** [comment]
I tried a couple of commands but couldn't make it work so I asked about in the prettierd repo https://github.com/fsouza/prettierd/issues/432#issuecomment-1819669422

**Comment by stevearc** [comment]
Closing since this seems to be a prettierd issue
