### ISSUE TITLE
bug: csharpier pipe to stdin doesn't work

### ISSUE THREAD

**Issue by rpisarew** [stevearc/conform.nvim#204]
### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1699524327

### Operating system/version

MacOS Ventura 13.6

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

00:41:16[DEBUG] Running formatters on /Users/lowm4n/code/test/Program.cs: { "csharpier" }
00:41:16[INFO] Run csharpier on /Users/lowm4n/code/test/Program.cs
00:41:16[DEBUG] Run command: { "dotnet-csharpier", "--write-stdout" }
00:41:20[WARN] Formatter 'csharpier' timeout
00:41:21[DEBUG] Running formatters on /Users/lowm4n/code/test/Program.cs: { "csharpier" }
00:41:21[INFO] Run csharpier on /Users/lowm4n/code/test/Program.cs
00:41:21[DEBUG] Run command: { "dotnet-csharpier", "--write-stdout" }
00:41:22[INFO] csharpier exited with code 137
00:41:22[DEBUG] csharpier stdout: { "" }
00:41:22[DEBUG] csharpier stderr: { "" }
00:41:25[WARN] Formatter 'csharpier' timeout
00:41:27[INFO] csharpier exited with code 137
00:41:27[DEBUG] csharpier stdout: { "" }
00:41:27[DEBUG] csharpier stderr: { "" }

### Describe the bug

The formatter timeouts because it does nothing receive in stdin.

Workarround (https://github.com/LazyVim/LazyVim/issues/2016):
```
  {
    "stevearc/conform.nvim",
    opts = {
      formatters = {
        csharpier = {
          args = { "--write-stdout", "$FILENAME" },
        },
      },
    },
  },
```

### Steps To Reproduce

1. Get https://github.com/LazyVim/starter
2. Run `:LazyExtras`
3. Add `lang.omnisharp`
4. Open a C# file and try to format

### Expected Behavior

File should be formatted.

### Minimal example file

Program.cs
```csharp
Console.WriteLine("Hello, World!");
```

**Comment by stevearc** [comment]
[According to the docs](https://github.com/belav/csharpier/blob/ef795385ba4b83a0b61a56287fd380cc63000dee/Docs/CLI.md#--write-stdout), it should format text that is piped to stdin. Does it work if you remove all of the args? If not, what happens when you run `csharpier < Program.cs`?

**Comment by rpisarew** [comment]
Removing the args does not help. I'm on a unix like system, if execute `cat Program.cs. | dotnet-csharpier` it works without any issues and prints the formatted result to stdout.

**Comment by stevearc** [comment]
Can you set `log_level = vim.log.levels.TRACE` and show me the log file from running csharpier when you remove all of the args? Preferably with a small example file because it will log the entire contents.

**Comment by rpisarew** [comment]
```
18:32:55[TRACE] Applying formatting to /Users/lowm4n/code/test/Program.cs
18:32:55[TRACE] Comparing lines { 'Console.WriteLine("Hello, World!");', "", "if (true) {", '          var foo = "bar";', "}" } and { 'Console.WriteLine("Hello, World!");', "", "if (true) {", '          var foo = "bar";', "}" }
18:32:55[TRACE] Diff indices {}
18:32:55[TRACE] Applying text edits: {}
18:32:55[TRACE] Done formatting /Users/lowm4n/code/test/Program.cs
18:32:55[WARN] Formatter 'csharpier' timeout
18:32:57[INFO] csharpier exited with code 137
18:32:57[DEBUG] csharpier stdout: { "" }
18:32:57[DEBUG] csharpier stderr: { "" }
```

**Comment by sergiomb2** [comment]
By the way, Lazyvim fixed it like thia:  https://github.com/LazyVim/LazyVim/issues/3124 , https://github.com/LazyVim/LazyVim/pull/3107
