### ISSUE TITLE
bug: embedded text detected by treesitter but not formatted by conform

### ISSUE THREAD

**Issue by thenbe** [stevearc/conform.nvim#207]
### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1693350652

### Operating system/version

 - system: `"x86_64-linux"`  - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.1

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

```
Log file: /home/nbe/projects/playground/repro-conform-embed/.repro//state/nvim/conform.log
          13:49:53[INFO] Run prettier on /home/nbe/projects/playground/repro-conform-embed/foo.ts
          13:49:53[DEBUG] Run command: { "prettier", "--stdin-filepath", "/home/nbe/projects/playground/repro-conform-embed/foo.ts" }
          13:49:53[DEBUG] prettier exited with code 0
          13:49:53[INFO] Run injected on /home/nbe/projects/playground/repro-conform-embed/foo.ts

Formatters for this buffer:
prettier ready (html, typescript)
injected ready (typescript)

Other formatters:
```

### Describe the bug

Is it a fair assumption to expect the formatter to work whenever treesitter syntax highlighting is working? If so, then this is a bug.

### Steps To Reproduce

1. Create a `foo.ts` file with the following contents:

   ```typescript
   foo.innerHTML = ` <div>   hello</div>  `;
 
   bar.innerHTML = `
   <div>   world
   </div>
   `;
   ```

1. Observe that treesitter has detected the embedded HTML text. Observe that the embedded HTML text has proper HTML syntax highlighting.

1. Run `:lua require "conform".format()`

1. .
   - ACTUAL:   Observe that none of the embedded HTML text is formatted.
   - EXPECTED: Observe that all embedded text is formatted.

### Expected Behavior

.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
    {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua", "typescript", "html" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
        formatters_by_ft = {
          ["typescript"] = { "prettier", "injected" },
          ["html"] = { "prettier" },
        }
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by thenbe** [comment]
Extra context:

The query responsible for detecting this particular embedded text is defined [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/8199529bc42ab275786d2f2cc83903f35ff6db9e/queries/ecma/injections.scm#L103-L121).

Custom injection queries are also affected by this issue. An relevant example (and a possible solution?) can be found [here](https://github.com/LostNeophyte/null-ls-embedded/issues/10).

**Comment by stevearc** [comment]
I made a change for #205 that partially fixes this. The one remaining pieces is that the injected formatter currently expects the injected language to occupy entire lines. It can't handle an inline injection like you have on the first line of your example file. I'll add support for that when I get time.
