### ISSUE TITLE
tsx formatter not active

### ISSUE THREAD

**Issue by BeatScherrer** [stevearc/conform.nvim#218]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1594+g4972c8048

### Operating system/version

6.6.2-arch1-1

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

log file empty

### Describe the bug

when trying to use the biome formatter for tsx files as following:

```
      formatters_by_ft = {
        tsx = { "biome" }
      },
```

the formatter is listed as ready on `ConformInfo` but not active for the buffer.

using the fallback works as expected:
```
      formatters_by_ft = {
        ["_"] = { "biome" }
      },
```

so this seems like the filetype is not recognized properly.

### Steps To Reproduce

```

* open a tsx file
* output `ConformInfo`
* try to format the file
```

set formatter for .tsx files

### Expected Behavior

formater is active for a tsx file and in fact formats it.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        formatters_by_ft = {
          tsx = { "biome" }
        }
      })
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "biome"
      },
    },
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

```

**Comment by stevearc** [comment]
Check your filetype. For historical reasons, `.tsx` files have the filetype `typescriptreact`. Try using that in the `formatters_by_ft` map

**Comment by marko911** [comment]
Anyone know by any chance How i can get biome + conform to work in Astrovim setup ?
