### ISSUE TITLE
How to use EslintFixAll command as formatter?

### ISSUE THREAD

**Issue by kola-web** [stevearc/conform.nvim#222]

**Comment by kola-web** [comment]
![image](https://github.com/stevearc/conform.nvim/assets/46446884/3567b08b-fe29-478a-bd95-30b97102c20b)
I tried a custom formatter but it didn't work

**Comment by fbuchlak** [comment]
Is there any difference in running cmd and using eslint executable?
Conform expects command to be executable. E.g. [eslint_d](https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/eslint_d.lua). If you don't have `eslint_d`, creating `eslint` should be straightforward.

If you still want to use `EslintFixAll` take a look at [LazyVim eslint lsp configuration](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/linting/eslint.lua). With lsp_fallback enabled and this lsp configuration formatting should work.

**Comment by stevearc** [comment]
Commands are not supported as formatters, due to the fact that they have a radically different interface. See #193 for more

**Comment by 1-800-jono** [comment]
Hi, don't completely understand what @fbuchlak is saying - this is all new to me. But is there an `EslintFixAll` equivalent  using `conform`?

**Comment by nicanordlc** [comment]
So basically we shouldn't use `conform` to format with eslint ?

**Comment by nicanordlc** [comment]
My solution: I disabled lsp fix on conform and use the `EslintFixAll` as a custom formatter. Here's the commit on my repo: https://github.com/nicanordlc/nvim/commit/864965bfe8d0a20e66f3e0a52f21bc89a9d71843
