### ISSUE TITLE
Feature Request: Display location of the formatters command

### ISSUE THREAD

**Issue by agoodshort** [stevearc/conform.nvim#225]
## Description

Is there an interest to display the location of the command found and used for a formatter in `:ConformInfo`?

Let me know your thoughts, and I can help with a PR if you want.

## Example scenario

- latest version of `prettier` installed globally (or/and through [mason.nvim](https://github.com/williamboman/mason.nvim)) for some random js file editing on my machines
- specific versions of `prettier` installed as `devDependencies` in my projects

How can I confirm/know that when I am in my projects, the `devDependencies prettier` will be used before my globally installed ones?

## Request behaviour

Display the location of the formatter command used to format the buffer. For example:

![image](https://github.com/stevearc/conform.nvim/assets/33832653/3d2a1203-bcbb-4153-b782-5aed7b05dadd)

## Actual behaviour

At the moment, the only cue available about the location are if the formatter is available or not, either global or as a project `devDependencies`

### Scenario 1

Prettier installed:
- globally ❌
- mason ❌
- project `devDependencies` ❌

![image](https://github.com/stevearc/conform.nvim/assets/33832653/60a3b9ae-b4d4-4386-a987-665d836e088a)

_Side note: in this scenario, running the formatting command does not display an error message even though a formatter is unavailable. Do you want a separate issue for this?_

### Scenario 2

Prettier installed:
- globally ❌
- mason ❌
- project `devDependencies` ✔️

![image](https://github.com/stevearc/conform.nvim/assets/33832653/375c11b8-d610-4006-8317-91a10e802a69)

### Scenario 3

Prettier installed:
- globally ✔️
- mason ❌
- project `devDependencies` ✔️

![image](https://github.com/stevearc/conform.nvim/assets/33832653/ede2f37d-896f-449c-a985-884cf5313a2d)

![image](https://github.com/stevearc/conform.nvim/assets/33832653/1d23ae21-74d4-4238-9bd0-38282e9119b3)

### Scenario 4

Prettier installed:
- globally ✔️
- mason ✔️
- project `devDependencies` ✔️

![image](https://github.com/stevearc/conform.nvim/assets/33832653/27ae02f3-28ff-451d-a5eb-dc757f0844e3)

![image](https://github.com/stevearc/conform.nvim/assets/33832653/5ef06977-4184-4fa1-b600-bf68fae461d7)

## Workaround

As far as I understood from the code base and documentation, I could configure the order of the commands based if they are found by `find_executable` util. But this will still not give me the information I am after.

For example, in order:
1. project
2. mason

```lua
require("conform").setup({
  formatters = {
    yamlfix = {
      command = require("conform.util").find_executable({ "node_modules/.bin/prettier", "$XDG_DATA_HOME/nvim/mason/bin/prettier" }, "prettier"),
    },
  },
})
```

**Comment by stevearc** [comment]
This seems like a fine addition; I would review a PR for it

Note that the lack of errors when a formatter executable is not found is an intentional choice. It allows you to keep the same config across multiple systems and possibly dev environments without seeing errors because certain formatting tools are not installed.
