### ISSUE TITLE
bug: text passed to formatters for injected regions in TS/JS files includes code from outside region

### ISSUE THREAD

**Issue by b0o** [stevearc/conform.nvim#229]
### Neovim version (nvim -v)

v0.10.0-dev-1711+g65de1a22c4

### Operating system/version

Arch Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

```
01:21:50[DEBUG] Running formatters on /tmp/repro/repro.js: { "injected" }
01:21:50[INFO] Run injected on /tmp/repro/repro.js
01:21:50[DEBUG] Injected format glsl:5:10: { "tee" }
01:21:50[INFO] Run tee on /tmp/repro/repro.js.glsl
01:21:50[DEBUG] Run command: { "tee", "/tmp/repro/.repro//intercepted.glsl" }
01:21:50[DEBUG] tee exited with code 0
```

### Describe the bug

When running formatters on injected code blocks within JavaScript/TypeScript, code from outside of the block is sent to the formatter. 

To demonstrate this, in the minimal `init.lua` below, I've set up conform to use the `injected` formatter for JS files. I plan to demonstrate this with `glsl` injected code blocks, so for the `glsl` filetype, I've set up a simple formatter that uses the `tee` command to log stdin to a file and print stdin to stdout. By looking at the file written by `tee`, we can see exactly what text was sent to the formatter.

### Steps To Reproduce

1. `nvim -u repro.lua`
2. make sure to restart neovim after the initial lazy install so that treesitter loads correctly
3. `nvim -u repro.lua repro.js`
4. `:write` to trigger format on save
5. take a look at `.repro/intercepted.glsl` to see what was sent to the formatter, it will look like this:

```javascript
const vert = glsl`
  void main() {
    vec4 position = vec4(0.0, 0.0, 0.0, 1.0);
    position = position * projectionMatrix;
    gl_Position = position;
  }
```

As you can see, the entire line where the start of the injected region occurs is sent to the formatter, including code that's not intended to be part of the injected region.

### Expected Behavior

I would expect `intercepted.glsl` to look like this:

```glsl

  void main() {
    vec4 position = vec4(0.0, 0.0, 0.0, 1.0);
    position = position * projectionMatrix;
    gl_Position = position;
  }
```

### Minimal example file

```js
// This is a test

const foo = "bar";

const vert = glsl`
  void main() {
    vec4 position = vec4(0.0, 0.0, 0.0, 1.0);
    position = position * projectionMatrix;
    gl_Position = position;
  }
`;

const hello = "world";
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        format_on_save = {
          lsp_fallback = true,
          timeout_ms = 500,
        },
        formatters = {
          tee = {
            command = "tee",
            args = { root .. "/intercepted.glsl" },
          },
        },
        formatters_by_ft = {
          glsl = { "tee" },
          javascript = { "injected" },
        },
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          "javascript",
          "glsl",
        },
        highlight = {
          enable = true,
        },
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by stevearc** [comment]
Looks related to #224. I think I know how to fix it, just need to find the time
