### ISSUE TITLE
feature: Biome formatter

### ISSUE THREAD

**Issue by liamwh** [stevearc/conform.nvim#231]
[Biome](https://biomejs.dev/formatter/#use-the-formatter-with-the-cli) won the [prettier in Rust contest](https://prettier.io/blog/2023/11/27/20k-bounty-was-claimed), with >95% compatibility with Prettier. Is it an idea to directly support Biome in conform somehow?

**Comment by Uzaaft** [comment]
Conform.nvim works with biome.
