### ISSUE TITLE
bug: black formatter error

### ISSUE THREAD

**Issue by Blxckmage** [stevearc/conform.nvim#248]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

Debian GNU/Linux 12 (bookworm) on Windows 10 x86_64

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /home/blackmage/.local/state/nvim/conform.log
          20:02:26[DEBUG] Run command: { "black", "--stdin-filename", "/home/blackmage/workspace/program/test.py", "--quiet", "-" }
          20:02:26[INFO] black exited with code 123
          20:02:26[DEBUG] black stdout: { '            fruits = ["apple", "banana", "cherry"]\r', "for x in fruits:\r", "    print(x)\r", "" }
          20:02:26[DEBUG] black stderr: { "error: cannot format /home/blackmage/workspace/program/test.py: cannot use --safe with this file; failed to parse source file AST: unexpected indent (<unknown>, line 1)", "This could be caused by running Black with an older Python version that does not support new syntax used in your source file.", "" }
          20:02:26[ERROR] Formatter 'black' error: error: cannot format /home/blackmage/workspace/program/test.py: cannot use --safe with this file; failed to parse source file AST: unexpected indent (<unknown>, line 1)
          This could be caused by running Black with an older Python version that does not support new syntax used in your source file.

### Describe the bug

I am getting some issues while using the black formatter, I can use other formatter in other languages but only black which isn't working on my python code.

and the log says that it's caused by running Black with an older Python version(?)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. nvim (any python code)
2. save file to format

### Expected Behavior

Black formatter to work.

### Minimal example file

            fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        		require("conform").setup({
			log_level = vim.log.levels.DEBUG,
			format_on_save = {
				timeout_ms = 3000,
				async = false,
				quiet = false,
			},
			formatters_by_ft = {
				javascript = { "prettier" },
				typescript = { "prettier" },
				javascriptreact = { "prettier" },
				typescriptreact = { "prettier" },
				css = { "prettier" },
				html = { "prettier" },
				json = { "prettier" },
				yaml = { "prettier" },
				markdown = { "prettier" },
				lua = { "stylua" },
				python = { "black" },
			},
		})

      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by bartels** [comment]
Hmm, I think this is a bug with `black` itself and not `conform.nvim` so you might need to raise an issue there.

You can see the error by running black directly on your example file outside of nvim

```sh
black indented_list.py
error: cannot format indented_list.py: cannot use --safe with this file; failed to parse source file AST: unexpected indent (<unknown>, line 1)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.

Oh no! 💥 💔 💥
1 file failed to reformat.
```
Probably the issue is invalid python file due to the bad indentation.

Anyway, it seems that running black with the `--fast` option does work (instead of the default, which is `--safe`).   Although I'm not sure it would be wise for conform to change the default option.

Using this config in the conform setup works for me:

```lua
...
  formatters = {
    black = {
      prepend_args = { '--fast' },
    },
  },

```

**Comment by Blxckmage** [comment]
thank you so much!! using `--fast` with black resolves the issue. closing this now. 👍
