### ISSUE TITLE
bug: black formatter results in blank buffer if using `--force-exclude` option

### ISSUE THREAD

**Issue by bartels** [stevearc/conform.nvim#249]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /conform_bug/.repro//state/nvim/conform.log
          23:56:48[INFO] Run black on /conform_bug/test.py
          23:56:48[DEBUG] Run command: { "black", "--stdin-filename", "/conform_bug/test.py", "--quiet", "-" }
          23:56:48[DEBUG] Run CWD: /conform_bug
          23:56:48[DEBUG] black exited with code 0

### Describe the bug

`black` can be configured to ignore files that match a regex pattern with the `--force-exclude` option. Matching files will be ignored by black and not formatted. A python project can add this config option to `pyproject.toml` file using `tools.black.force-exclude`

Running `conform.format()` on a file ignored by `black` results in an empty buffer.

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

Here's a gist: https://gist.github.com/bartels/c71e95c5d73f96952c184567ac4a19cd

### Expected Behavior

The buffer should not be modified since black is set to ignore them.

### Minimal example file

test.py

```python
#!/usr/bin/env python

# This file is ignored by black with `force-exclude` option.
# Any files contents will do. conform.format() will result in a blank buffer

print("No, please don't delete me!!!")
```
pyproject.toml

```toml
# Ignore test.py
[tool.black]
force-exclude = '''
^/test\.py
'''
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        formatters_by_ft = {
          python = { 'black' },
        }
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

When you run `black` on an ignored file, it will not output the file contents, but  it does  have a return code of `0`.

```sh
cat test.py | black --quiet --stdin-filename "$PWD"/test.py -
echo $?
```

The empty output is likely the problem. Can conform handle this case?  Is there a way to configure conform to ignore empty output from formatters?

**Comment by stevearc** [comment]
Hmmm...ideally black would output the unformatted file contents in this case. Outputting nothing is kind of a weird behavior :/

I think the best we can do here is add a hack that checks if the output is empty but the input is not (specifically, the input has some non-whitespace characters) and abort the formatting in that case.
