### ISSUE TITLE
How to format on save when using ":x"

### ISSUE THREAD

**Issue by nbari** [stevearc/conform.nvim#26]
Hi, first of all, many thanks for sharing and all your time on this, I have been struggling to find a plugin to format, and fortunately just found `conform` I am using it as a replacement for `null-ls` and so far working pretty good, but I don't know if I have more a configuration issue or bug when trying to exit using `:x` the file is not formatted, if I use `:w` or exit with `:wq` the file gets formatted, also I have an alias `<leader>ff` to format and works fine, attached is my current configuration:

```lua
local M = {
    "stevearc/conform.nvim",
     event = "VeryLazy"
}

M.keys = {
    {
        "<leader>ff",
        function()
            require("conform").format({
                lsp_fallback = true
            })
        end
    }
}

M.config = function()
    require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        format_on_save = {
            timeout_ms = 500,
            lsp_fallback = true
        },
        formatters_by_ft = {
            lua = {
                "lua"
            },
            json = {
                "json"
            }

        },
        formatters = {
            lua = {
                command = "lua-format",
                args = {
                    "--break-after-table-lb",
                    "--chop-down-table",
                    "--column-table-limit=1",
                    "--no-keep-simple-function-one-line"
                }
            },
            json = {
                command = "jq",
                args = {
                    "--indent",
                    "2"
                }
            }
        }
    })
end

return M
```

Any ideas?

**Comment by stevearc** [comment]
One thing to note is `:x` only writes if there are changes to the buffer. If it doesn't write, then it won't trigger the `BufSavePre` autocmd so no formatting will happen. In your example, is the buffer you are trying to format modified or not before you do `:x`?
