### ISSUE TITLE
feature request: dry run formatters

### ISSUE THREAD

**Issue by bpjordan** [stevearc/conform.nvim#262]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Provide a way to "dry run" formatters, i.e. run formatters and retrieve diffs from them, but just return them to the user without actually applying them to the buffer.

### Provide background

I have a set up to format on write, but for work I often make small changes to large files that aren't formatted. I would like to be able to check if a file is formatted in a `BufOpen` autocmd and disable the autoformatting if it isn't already formatted. That way I can make the change without formatting the whole file, or manually enable formatting if I want to.

### What is the significance of this feature?

nice to have

### Additional details

I would be happy to make a PR to implement this.

My proposed API changes would be as follows:

- add a `dry_run` boolean to the `opts` table for `conform.format()`
- skip the call to `apply_format` when it is enabled
- add a second return value to `conform.format` with a table of the diffs
- add the same table as a second argument to `callback`

So my use case mentioned above could be accomplished with something like:

```lua
vim.api.nvim_create_autocmd('BufRead', {
pattern = "*",
callback = function(e)
    require('conform').format({
        dry_run = true,
        async = true,
        callback = function(err, formatter_results)
            for _, result in pairs(formatter_results) do
                if result.diff ~= nil then
                    vim.b[e.bufnr].disable_autoformat = true
                    return
                end
            end
        end}
end})
```

**Comment by stevearc** [comment]
This is a neat idea, and if it can be done with relatively minimal API changes that are pretty clean, I'm on board. The API that makes the most sense to me would be:

- Add a second parameter to the `callback` function that is a boolean. This indicates if any changes were applied.
- Add a `dry_run` option to format() that will skip applying changes, but keep the same logic for that `formatted` parameter.

This way we don't expose more information than is actually needed, we neatly sidestep the issue of "how do we combine normal formatter diffs with LSP format diffs", and it's something that could be useful for non-dry_runs as well. What do you think?

**Comment by bpjordan** [comment]
> This is a neat idea, and if it can be done with relatively minimal API changes that are pretty clean, I'm on board. The API that makes the most sense to me would be:
> 
>     * Add a second parameter to the `callback` function that is a boolean. This indicates if any changes were applied.
> 
>     * Add a `dry_run` option to format() that will skip applying changes, but keep the same logic for that `formatted` parameter.
> 
> 
> This way we don't expose more information than is actually needed, we neatly sidestep the issue of "how do we combine normal formatter diffs with LSP format diffs", and it's something that could be useful for non-dry_runs as well. What do you think?

I like this as well. I wasn't sure if you'd want just the boolean return value, since it does limit the usefulness of this change, but I'm on board with leaving it that way since it does massively simplify the implementation.
