### ISSUE TITLE
bug: Injected formatter... does nothing?

### ISSUE THREAD

**Issue by magnuslarsen** [stevearc/conform.nvim#270]
### Neovim version (nvim -v)

NVIM v0.10.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22.04

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Here I ran "format" thrice:

08:11:47[DEBUG] Running formatters on /home/mlar/test2.py: { "injected" }
08:11:47[INFO] Run injected on /home/mlar/test2.py
08:11:47[DEBUG] Running LSP formatter on /home/mlar/test2.py

08:11:51[DEBUG] Running formatters on /home/mlar/test2.py: { "injected" }
08:11:51[INFO] Run injected on /home/mlar/test2.py
08:11:51[DEBUG] Running LSP formatter on /home/mlar/test2.py

08:12:06[DEBUG] Running formatters on /home/mlar/test2.py: { "injected" }
08:12:06[INFO] Run injected on /home/mlar/test2.py
08:12:06[DEBUG] Running LSP formatter on /home/mlar/test2.py

### Describe the bug

(slight follow-up to https://github.com/stevearc/conform.nvim/issues/224）

Hi Steve, thanks again for an awesome plug-in!

It seems that injected formatter does... nothing? 

The below Treesitter injections works (the highlighting is correctly injected) - and the SQL/JSON formatters work, if I copy the contents to a `tmp.sql` / `tmp.json` file

`.config/nvim/queries/python/injections.scm`:
```lisp
; Variables ending in "_sql" and "_SQL"
(expression_statement
  (assignment
    left: (identifier) @_left (#match? @_left "(_sql|_SQL)$")
    right: (string
      (string_content) @injection.content
      (#set! injection.language "sql")
    )
  )
)

; Variables ending in "_json" and "_JSON"
(expression_statement
  (assignment
    left: (identifier) @_left (#match? @_left "(_json|_JSON)$")
    right: (string
      (string_content) @injection.content
      (#set! injection.language "json")
    )
  )
)
```

`test2.py`:
![image](https://github.com/stevearc/conform.nvim/assets/7879747/0f544e42-ddfa-470d-99bf-979afd432310)

This is also the case for rust injections (the examples would just be too large)

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. Create the files from the `Minimal example file`-step
2. `nvim -u repro.lua test2.py`
3. Run `:lua require("conform").format()`

### Expected Behavior

I'd expect the formatters to run, or at least indicate why they didn't

### Minimal example file

Python file `test2.py`:
```py
test_sql = """
    select a,b from myTable where a>b
"""

test_json = """
{ "this": "is a value", "that": "is j'son" }
"""

```

`.repro/config/nvim/queries/python/injections.scm`:
```lisp
; Variables ending in "_sql" and "_SQL"
(expression_statement
  (assignment
    left: (identifier) @_left (#match? @_left "(_sql|_SQL)$")
    right: (string
      (string_content) @injection.content
      (#set! injection.language "sql")
    )
  )
)

; Variables ending in "_json" and "_JSON"
(expression_statement
  (assignment
    left: (identifier) @_left (#match? @_left "(_json|_JSON)$")
    right: (string
      (string_content) @injection.content
      (#set! injection.language "json")
    )
  )
)
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        formatters_by_ft = {
          json = { "fixjson" },
          sql = { "sql_formatter" },
          ["*"] = { "injected" }
        }
      })
    end,
  },
  -- add any other plugins here
	{
		"nvim-treesitter/nvim-treesitter",
		config = function(_, _)
			require("nvim-treesitter.configs").setup({
				ensure_installed = { "python", "json", "sql" },
				auto_install = true,
				highlight = { enable = true },
			})
		end,
	},

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by magnuslarsen** [comment]
Interestingly enough, I get the same "error" in markdown files:
`test.md`:
````
```json
{"key": "value", "key2": "value"}
```

```sql
select a,b from Table where a>b
```
````
Highlighting is correct:

![image](https://github.com/stevearc/conform.nvim/assets/7879747/7ec8dc47-46df-4e14-8489-fc88b26b3145)

Running `:lua require("conform").format()` yields the same log file, and no actual formatting:
```
08:43:23[DEBUG] Running formatters on /tmp/test.md: { "injected" }
08:43:23[INFO] Run injected on /tmp/test.md
```

**Comment by stevearc** [comment]
A recent change to the formatter broke it _only_ on nightly. Should be working again.

**Comment by magnuslarsen** [comment]
Steven, you are a hero. Thanks for the very fast turn around!
