### ISSUE TITLE
Question: range formatting on lsp fallback formatters

### ISSUE THREAD

**Issue by tranzystorekk** [stevearc/conform.nvim#285]
I want to ask before I commit to debugging something that has a simple answer: does conform do its range formatting magic with lsp fallback formatters that don't support range format themselves?

I ran into an issue where my rust-analyzer only formats whole buffers and does nothing if I try to do a range format, while e.g. lua_ls formats both no problem. I also tried setting explicit `rustfmt` formatter in the conform config and the issue goes away.

If the answer is yes then I'll try to create a repro scenario and submit a bug report.

**Comment by stevearc** [comment]
No, at the moment range formatting with LSP only works if the LSP server itself supports range formatting. Adding support would be doable, it would just take some time and effort.
