### ISSUE TITLE
Question/Bug: I can't get conform to format my code properly with eslint/prettier.

### ISSUE THREAD

**Issue by Saveljeffjonatan** [stevearc/conform.nvim#291]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Macos Sonoma 14.3

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /Users/quacksensei/.local/state/nvim/conform.log
          19:16:12[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:16:14[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:16:15[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:16:16[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:17:18[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:17:28[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:18:17[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx
          19:18:18[DEBUG] Running LSP formatter on /Users/quacksensei/git/work/Phoenix/src/pages/Appointments/Appointments.tsx

Formatters for this buffer:
LSP: tsserver
trim_whitespace ready (_) /usr/bin/awk
codespell unavailable: Command not found

Other formatters:
gofmt ready (go) /usr/local/go/bin/gofmt
goimports unavailable: Command not found
prettier ready (javascript, typescript) /Users/quacksensei/git/work/Phoenix/node_modules/.bin/prettier
prettierd unavailable: Command not found
stylua ready (lua) /Users/quacksensei/.local/share/nvim/mason/bin/stylua

### Describe the bug

Doesn't seem to listen to my eslint settings.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Not sure, I could share my setup maybe?

### Expected Behavior

Format according to prettier with eslint as linted format in mind

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

![Screenshot 2024-02-07 at 19 24 33](https://github.com/stevearc/conform.nvim/assets/15213622/36ca5f89-e0a8-49cd-9a41-74c133a380e1)
![Screenshot 2024-02-07 at 19 24 44](https://github.com/stevearc/conform.nvim/assets/15213622/527b72de-5c6f-4a58-8895-aff4270e8dd6)

One is before save (proper syntax on my formatting)
The one with errors is what happen when I do :w

**Comment by Saveljeffjonatan** [comment]
Update: might be related to how prettier formats the code. If I install Eslint LSP and do a EslintFixAll then the problem goes away and it formats correctly.

**Comment by Saveljeffjonatan** [comment]
Managed to solve this issue, turns our that I wasn't looking at `typescriptreact` but just typescript...

**Comment by borasemiz** [comment]
> Managed to solve this issue, turns our that I wasn't looking at `typescriptreact` but just typescript...

For the documentation writes of this plugin:
Is there any way to see what sort of file types are accepted? I mean, there are many ways to type "javascript":

- javascript
- JavaScript
- js
- JS
- Js

With react too:

- javascriptreact
- jsx
- JavaScript-React

???

**Comment by Joecey** [comment]
> vim.api.nvim_create_autocmd("BufWritePre", {
>   pattern = { "*.ts", "*.tsx", "*.js", "*.jsx" },
>   callback = function()
>     local bufnr = vim.api.nvim_get_current_buf()
>     local clients = vim.lsp.get_clients({ buf = bufnr })
>     for _, client in ipairs(clients) do
>       if client.name == "eslint" then
>         vim.b.autoformat = false
>         vim.cmd("silent! LspEslintFixAll")
>         return
>       end
>     end
>   end,
> })

Legendary stuff thank you! using this with kickstart and just added this to the end of my conform configs. Now it works for me
