### ISSUE TITLE
question: how to execute an external command for formatting?

### ISSUE THREAD

**Issue by Delice0** [stevearc/conform.nvim#292]
### Neovim version (nvim -v)

0.9

### Operating system/version

latest mac

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

N/A

### Describe the bug

Is it possible to format java files by creating a keymap that executes following command: `mvn fmt:format` ?

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

N/A

### Expected Behavior

N/A

### Minimal example file

N/A

### Minimal init.lua

```Lua
N/A
```

**Comment by stevearc** [comment]
Yes, you'll need to define it as a custom formatter. Look at some of the examples here to see what the structure looks like
https://github.com/stevearc/conform.nvim/tree/master/lua/conform/formatters

You'll probably need to define `cmd`, `args`, `stdin`, and you may want `cwd`.
