### ISSUE TITLE
bug: docs contain extra tag `*required*`

### ISSUE THREAD

**Issue by CoderJoshDK** [stevearc/conform.nvim#294]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOs 14.2

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Not applicable

### Describe the bug

In the code comments, in the options section of the docs, there is a comment that is MD bold: `**`
https://github.com/stevearc/conform.nvim/blob/master/doc/conform.txt#L59. However, `ft=help` registers this as a tag. 

From what I could find, just updating https://github.com/stevearc/conform.nvim/blob/master/scripts/options_doc.lua#L45 's "bold" text with some different identifier, should fix it.

I know this is a super minor thing, but I figured I would say something. 

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Use telescope's `:Telescope help_tag` and search for `required`

### Expected Behavior

Code comments to not be registered in the help tags.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

Sorry for being so pedantic

**Comment by stevearc** [comment]
done
