### ISSUE TITLE
feature request: ability to disable formatter completely at runtime

### ISSUE THREAD

**Issue by Integralist** [stevearc/conform.nvim#295]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like a function (or Ex command) that I can call to disable the assigned formatter(s) for the current buffer.

### Provide background

I have a Markdown formatter which works great but there are a few projects (both work-related and personal) that are Markdown and require a specific _structure_ which the Markdown formatter messes with and causes my builds to break.

My solution so far as been to open up the file in `vi` or `nvim` with no config so that I can just edit the file, but then I lose all the other nice plugins that I use day-to-day.

I just need a way to say: for this file, don't format it. 

### What is the significance of this feature?

strongly desired

### Additional details

I'm sure I could write a custom function to disable this on a 'project' by 'project' basis, similar to what I've done [here](https://github.com/Integralist/nvim/blob/main/lua/plugins/lint-and-format.lua#L58-L64) with nvim-lint and not running a GitHub Actions linter on a non-GHA yaml file. But in this case there are two concerns with that...

1. I have to have a long list of 'projects' hard-coded into my config that needs to be maintained.
2. I don't want to have to go off to my config to edit it when I next start a new project that has this issue.

**Comment by stevearc** [comment]
Have you tried [this recipe?](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save)

**Comment by NullVoxPopuli** [comment]
can this be built in tho? it's frustrating to need this while editing, only to find out you have to exit, discard changes, edit your dotfiles, implement the recipe, and re-edit your files the same way

**Comment by stevearc** [comment]
You only have to edit your dotfiles once. The reason this functionality isn't built in is that there are a lot of ways that people want to customize when and how files get formatted. I know that if I begin to add these sorts of features, I'll get a bunch more issues and PRs from people that want to tweak the behavior for their use case or extend it to do just a little bit more. I can't handle that additional maintenance burden, so I'm keeping it simple and pushing off that last bit of configuration into the end user dotfiles.

That said, if you're in a pinch and need to write once without formatting you can do `:noau w` which is short for `:noautocmd write`. This will write the file without triggering any normal autocmds, including the ones that apply formatting.
