### ISSUE TITLE
Question: picking the correct formatter when multiple formatters exist within a monorepo

### ISSUE THREAD

**Issue by asilvadesigns** [stevearc/conform.nvim#299]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I have a use case where multiple formatters exist within a monorepo. For example, I have biome.json used in the root of the project, and prettier used in some nested apps. I register biome and prettier in formatters_by_ft, then when I invoked `require("conform").format(...` the correct formatter is not used.

As a work around, I've written a (bad) little function to determine the distance between the formatter config file and the buffer, whoever's path is shortest, use that formatter... it works but I'm sure the plugin author has already considered this use case.

I'd love to hear what I ought to be using to achieve the use case mentioned above.

Thanks so much!

### What is the significance of this feature?

nice to have

**Comment by asilvadesigns** [comment]
I'm doing this rn...

```lua
    vim.api.nvim_create_user_command("Format", function()
      local formatter = get_closest_formatter({
        biome = { "biome.json" },
        prettier = { ".prettierrc" },
        stylua = { "stylua.toml" },
      })

      if not formatter then
        print("formatter not found, using lsp")
        require("conform").format({ async = true, lsp_fallback = true })
      else
        print("formatting with " .. formatter[1])
        require("conform").format({
          async = true,
          formatters = formatter,
          lsp_fallback = false,
        })
      end
    end, {})
```

**Comment by stevearc** [comment]
You are doing the correct thing! I don't think it makes sense for conform to try to add some option to detect the closest formatter. That's a very particular operation that is likely going to be specific to whatever repo you are working in. Writing a custom function to detect the environment and pass the formatters in explicitly is 100% the correct approach.

**Comment by grindarius** [comment]
Hello @asilvadesigns I am having the same problem as what you had right now. Seeing how you solve this problem, could you share with us the implementation of `get_closest_formatter` please?. Thank you.

**Comment by nstylo** [comment]
@asilvadesigns I am also very keen on how you implemented your solution.

**Comment by asilvadesigns** [comment]
Whoops, didn’t see these, you can find it here
https://github.com/asilvadesigns/config/blob/87adf2bdc22c4ca89d1b06b013949d817b405e77/nvim/lua/plugins/conform.lua#L63

**Comment by asilvadesigns** [comment]
heads up, had a bug w/usage of os.homedir vs project root for fs.find... fix here: https://github.com/asilvadesigns/config/blob/ca4208d92b3cd3b1a2702d707545bbd951f16815/nvim/lua/plugins/conform.lua#L78

**Comment by asilvadesigns** [comment]
there was a bug w/ using `stop = vim.loop.os_homedir(),` where it would detect config files in home dir.. this is unideal, so I just put in `stop = require("lspconfig.util").root_pattern(".git")(v)` where "v" is a config file for the given formatter. Updates here. There's prolly other things wrong but is working for me rn. https://github.com/asilvadesigns/config/blob/78973b7368b4dbd4d7eba735307194bc9d71ff6a/nvim/lua/plugins/conform.lua#L74
