### ISSUE TITLE
LSP formatters not used as fallback?

### ISSUE THREAD

**Issue by xfzv** [stevearc/conform.nvim#30]
With [`elentok-format-on-save.nvim`](https://github.com/elentok/format-on-save.nvim/), I'm using:

```lua
return {
  "elentok/format-on-save.nvim",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    local format_on_save = require("format-on-save")
    local formatters = require("format-on-save.formatters")

    format_on_save.setup({
        c = formatters.lsp,
        cpp = formatters.lsp,
        json = formatters.lsp,
        jsonc = formatters.lsp,
        lua = formatters.lsp,
    })
  end,
}
```

and my files with these filetypes are formatted on saving.

The LSP I'm using:

| Filetype | LSP |
| -------- | --- |
| `c`, `cpp` | `clangd` |
| `json`, `jsonc` | `json-lsp` |
| `lua` | `lua-language-server` |

For `lua`, I guess it's using [CppCXY/EmmyLuaCodeStyle](https://github.com/CppCXY/EmmyLuaCodeStyle), which is the formatter from `lua-language-server`, as mentioned [here](https://github.com/LuaLS/lua-language-server/wiki/Formatter#formatter).

With `conform.nvim`, when saving in a `c`, `cpp`, `json`, `jsonc` or `lua` file, no formatting is applied at all. My config:

```lua
return {
  "stevearc/conform.nvim",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    require("conform").setup({
    formatters_by_ft = {
      css = { "prettierd" },
      javascript = { "prettierd" },
      markdown = { "prettierd" },
      sh = { "shfmt" },
      yaml = { "yamlfmt" },
    },
    format_on_save = {
        timeout_ms = 500,
        lsp_fallback = true,
    },
    })
  end
}
```

Am I missing something? I would expect `lsp_fallback = true` to use the formatter from the relevant LSP like [`elentok-format-on-save.nvim`](https://github.com/elentok/format-on-save.nvim/) does.

**Comment by stevearc** [comment]
I'm actually going to keep this open. I agree that this is surprising behavior, and I think I may want to refactor some things to make it more predictable.
