### ISSUE TITLE
bug: dart_format does not work

### ISSUE THREAD

**Issue by mhdos** [stevearc/conform.nvim#303]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

archlinux 6.7.4-arch1-1

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /home/mhdos/.local/state/nvim/conform.log
          15:16:03[INFO] Run dart_format on /home/mhdos/file.dart
          15:16:03[TRACE] Input lines: { "void main() { print('hello world'); }" }
          15:16:03[DEBUG] Run command: { "dart", "format" }
          15:16:03[TRACE] Applying formatting to /home/mhdos/file.dart
          15:16:03[TRACE] Comparing lines { "void main() { print('hello world'); }" } and { "void main() { print('hello world'); }" }
          15:16:03[TRACE] Diff indices {}
          15:16:03[TRACE] Applying text edits: {}
          15:16:03[TRACE] Done formatting /home/mhdos/file.dart
          15:16:03[WARN] Formatter 'dart_format' timeout
          15:16:03[INFO] dart_format exited with code 143
          15:16:03[DEBUG] dart_format stdout: { "" }
          15:16:03[DEBUG] dart_format stderr: { "" }

Formatters for this buffer:
dart_format ready (dart) /home/mhdos/.local/sdks/flutter/bin/dart

### Describe the bug

**dart_format** does not work.

note: if I manually run `dart format file.dart`, it works

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

n/a

### Expected Behavior

expected output:
```
void main() {
  print('hello world');
}
```

### Minimal example file

void main() { print('hello world'); }

**Comment by stevearc** [comment]
Looks like it's timing out. Either increase the `timeout_ms` or run it with `async = true`
