### ISSUE TITLE
conform doesn't seem to recognize any Mason installed formatter

### ISSUE THREAD

**Issue by gabrieldechichi** [stevearc/conform.nvim#308]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

09:02:27[DEBUG] Running formatters on C:\Users\gabri\.dotfiles\nvim\lua\plugins\conform.lua: {}
09:02:27[DEBUG] No formatters found for C:\Users\gabri\.dotfiles\nvim\lua\plugins\conform.lua
09:02:28[DEBUG] Running formatters on C:\Users\gabri\.dotfiles\nvim\lua\plugins\conform.lua: {}
09:02:28[DEBUG] No formatters found for C:\Users\gabri\.dotfiles\nvim\lua\plugins\conform.lua

### Describe the bug

`conform` doesn't seem to be recognizing any formatter installed with `mason`

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

Maybe I'm missing something obvious, but `conform` doesn't seem to be recognizing any formatter installed with `mason`. Is that expected behavior? And if so, how should I be installing formatters?

My config (using lazy.nvim):

```
return {
    'stevearc/conform.nvim',
    config = function()
        require('conform').setup({
            lua = { "stylua" },
            typescript = { { 'prettierd', "prettier" } },
            typescriptreact = { { 'prettierd', "prettier" } },
            javascript = { { 'prettierd', "prettier" } },
            javascriptreact = { { 'prettierd', "prettier" } },
            json = { { 'prettierd', "prettier" } },
            html = { { 'prettierd', "prettier" } },
            css = { { 'prettierd', "prettier" } },
            log_level = vim.log.levels.DEBUG,
            format_on_save = {
                -- These options will be passed to conform.format()
                timeout_ms = 500,
                lsp_fallback = false,
            },
        })
    end
}
```

I confirmed formatters are installed with Mason

![image](https://github.com/stevearc/conform.nvim/assets/15620434/a229c330-d740-45a5-97f7-ae5af0417cf4)

Output of `:ConformInfo` (in a lua file)
![image](https://github.com/stevearc/conform.nvim/assets/15620434/61640446-2f32-4bd7-b1c6-46bb11394b69)

**Comment by msyavuz** [comment]
Your setup call doesn't seem right to me. It lacks formatters_by_ft field.
```lua
require("conform").setup({
  formatters_by_ft = {
    lua = { "stylua" },
    -- Conform will run multiple formatters sequentially
    python = { "isort", "black" },
    -- Use a sub-list to run only the first available formatter
    javascript = { { "prettierd", "prettier" } },
  },
})
```

**Comment by gabrieldechichi** [comment]
Damn, brainfart, not sure how I missed that so many times in the documentation!

It works now, thanks for answering!
