### ISSUE TITLE
Is `["*"]` OK to define some formatters for all filetypes?

### ISSUE THREAD

**Issue by xfzv** [stevearc/conform.nvim#31]
As I was working on https://github.com/stevearc/conform.nvim/pull/29, I'm using locally:

```lua
return {
  dir = "/home/xfzv/.local/share/nvim/lazy/conform.nvim/",
  event = { "BufReadPre", "BufNewFile" },
  config = function()

    require("conform").setup({
    formatters_by_ft = {
      ["*"] = {
        formatters = {
          "trim_whitespace",
          "trim_newlines",
        },
        run_all_formatters = true,
      },
    },
    format_on_save = {
        timeout_ms = 500,
        lsp_fallback = true,
    },
    })
  end
}
```

Is using `["*"]` so that any filetype is matched OK? It seems to work just fine on my end but I'm wondering if there's a better way to do that, or if it could lead to any kind of breakage.

Thanks!

**Comment by stevearc** [comment]
Using `*` is supported and the correct way to do this, for now. You encountered the main problem in #30. I'll think about this some more and see if I want to change the behavior

**Comment by stevearc** [comment]
@xfzv Can you take a look at #33 and see if that works for you?
