### ISSUE TITLE
feature request: Add stylish-haskell to builtin formatters 

### ISSUE THREAD

**Issue by viniciusmiradouro** [stevearc/conform.nvim#317]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I use lazyVim and conform.nvim became the default formatter. The problem is that my formatter of choice for haskell is stylish-haskell which doesn't have out of the box support in conform.nvim and I don't know how to set it up.

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
@viniciusmiradouro yes, but it has been stuck waiting for an answer to a question since November. If you want to copy that PR and take it across the finish line that will probably get resolved faster.
