### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by helderberto** [stevearc/conform.nvim#346]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

**Which configuration?**
Filetype: `.lua`
Conform Version: Latest version

**Expected behavior**

Having an option out of the box, to switch between `Prettier` and `Eslint` to format files on saving, making it easiert to configure a `autocommand` which works for both tools.

### Provide background

I am trying to format files like `.tsx`, `.jsx`, `.js`, `.ts` on save, and use the tool configured into the project (Eslint or Prettier).

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
All the building blocks for this are already there. For example, [this recipe](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save) to make a command that toggles format-on-save could easily be repurposed to change which formatters you're using for a particular filetype. The only tricky part would be figuring out when you want to use one tool vs the other, but once you figure that out it should be straightforward to either automatically choose the right one or set up a manual toggle.

**Comment by helderberto** [comment]
> All the building blocks for this are already there. For example, [this recipe](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save) to make a command that toggles format-on-save could easily be repurposed to change which formatters you're using for a particular filetype. The only tricky part would be figuring out when you want to use one tool vs the other, but once you figure that out it should be straightforward to either automatically choose the right one or set up a manual toggle.

Thank you for the quick reply!
