### ISSUE TITLE
feature request: Option to use relative filepaths

### ISSUE THREAD

**Issue by jeraki** [stevearc/conform.nvim#349]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Is there a config option to have Conform send a file path relative to the working directory to the formatter? Or alternatively, is there an equivalent of the special `$FILEPATH` argument that will use a relative path?

I see in `conform.runner.build_context`, it's using `vim.api.nvim_buf_get_name`, which returns the absolute path, so I'm guessing it's not possible to do this currently, in which case consider this a feature request!

### Provide background

When I use Conform to format Ruby code with RuboCop, it fails and this error is returned by RuboCop:

```
"-s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked."
```

### What is the significance of this feature?

strongly desired

**Comment by sandrodz** [comment]
I've similar issue with phpcbf. I need to run it from project root.
My phpcs/phpcbf are dockerised tools, so Absolute path doesn't exist inside the container.

<img width="1072" alt="image" src="https://github.com/stevearc/conform.nvim/assets/8479569/1875129f-f3f9-4605-9d96-f468469084f9">

I thought CWD would help with this, but it doesn't

```
  formatters = {
    phpcbf = {
      cwd = require("conform.util").root_file({ ".editorconfig", "composer.json" }),
    },
  }
```

**Comment by stevearc** [comment]
You can now use the variable `$RELATIVE_FILEPATH` in formatter args and it will be a relative path to the file from the cwd.
