### ISSUE TITLE
bug: trim_whitespace adding newline at the end of the file

### ISSUE THREAD

**Issue by perrin4869** [stevearc/conform.nvim#35]
### Neovim version (nvim -v)

neovim-0.10.0_dev_aab06ed

### Operating system/version

slackware64-current

### Output of :ConformInfo

```
Log file: /home/perrin4869/.local/state/nvim/conform.log

Formatters for this buffer:
stylua ready (lua)
trim_whitespace ready (*)

Other formatters:
eslint_d ready (typescript, javascriptreact, typescriptreact, javascript)
prettier ready (json)
prettierd unavailable: Command not found

```

### Describe the bug

when running `require("conform").format`, a newline is added at the end of a lua file.

### Steps To Reproduce

for example:

```
$ cat foo.lua                                                                                                                                                        
local omg = "foo"
```

running `conform.format` will cause the file to become

```
$ cat foo.lua                                                                                                                                                        
local omg = "foo"

```

### Expected Behavior

Does not result in a newline at the end of the file

**Comment by stevearc** [comment]
This is an issue with pipelined formatters (it's running `stylua` and then `trim_whitespace`). I'll see if I can get a fix soon

**Comment by stevearc** [comment]
Should be fixed now!
