### ISSUE TITLE
question: is there a way to disable autoformat on save in the current buffer?

### ISSUE THREAD

**Issue by daniele821** [stevearc/conform.nvim#374]
currently, i have stylua set as the formatter_by_ft for lua, and also have lsp_fallback enabled in format_on_save. 

I sometimes do not want to format, thus i would like to disable formatting on save. But to do that, right now, i have to manually change the configuration and delete stylua in formatter_by_ft and set lsp_fallback in format_on_save as false.

Is there a way to disable all formatting on save happening in the current buffer?

If not, I think it would be a really useful feature

**Comment by gegoune** [comment]
`:h noautocmd` (use with `w`).

**Comment by daniele821** [comment]
damn, i feel stupid now. I just spent hours trying to think about how to do that lol.

Altough i do would still like to have a way to temporarely disable formatting on save, thus allowing me to only write :w instead of :noautocmd w everytime i want to save. Especially since this disables all autocmd run with :w, i have other things which rely on that autocmd.

But yeah it's already a good partial fix to my problem. Thanks

**Comment by deragon** [comment]
Is there a way to have it on during all the time the file is opened?  One needs to forget to save with the command 'noautocmd w' only once and the file gets saved formatted without realizing it, and then when git diff time happens before the commit, I have to undo all the formatting that has been added.

I asks AIs for assistance and search the web to novail for finding a solution.
