### ISSUE TITLE
Question: Configuring csharpier

### ISSUE THREAD

**Issue by Catacomba** [stevearc/conform.nvim#379]
I've configured a c# formatter by adding c_sharp = 'csharpier'. 
Info: 
- csharpier installed globally on my machine 
- added a .csharpierrc.json with the indent changed from 4 to 2 in my project (in the same folder as the .cs file)
- when running :ConformInfo on a .cs file, the formatter for this buffer has Omnisharp listed, meanwhile csharpier is listed under 'other formatters' which is confusing, since i have lsp_fallback set to false... 
- i have omnisharp installed with all default settings.

My config:
 ```lua
{ -- Autoformat
    'stevearc/conform.nvim',
    opts = {
      notify_on_error = true,
      format_on_save = function(bufnr)
        return {
          timeout_ms = 500,
          lsp_fallback = false,
        }
      end,
      formatters_by_ft = {
        lua = { 'stylua' },
        c_sharp = { 'csharpier' },
    },
},
```
When I `:w` the formatter does nothing. If I set lsp_fallback to true however, the omnisharp formatter is used. What am i doing wrong?

**Comment by msyavuz** [comment]
I think the filetype for csharp is "cs" not "c_sharp". Maybe try with that?

**Comment by Catacomba** [comment]
Using "cs" instead of "c_sharp" worked! 
Apearently I wrongly assumed i had to use some keyword, because in the setup the example uses lua, python, javascript... 
 ```lua
 formatters_by_ft = {
    lua = { "stylua" },
    -- Conform will run multiple formatters sequentially
    python = { "isort", "black" },
    -- Use a sub-list to run only the first available formatter
    javascript = { { "prettierd", "prettier" } },
  },
```
Afterwards i went and searched for cs/csharp/c_sharp and found a mapping in 
```lua
lang_to_ext = {
  ...
  c_sharp = "cs",
  ...
}
```
after which I assumed I had to use c_sharp and that it will be mapped to .cs files.
Anyway... thanks for the advice!

**Comment by msyavuz** [comment]
No problem! Feel free to close the issue
