### ISSUE TITLE
How to add new formatter ?

### ISSUE THREAD

**Issue by mrt181** [stevearc/conform.nvim#381]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to a add `dotnet format` that uses `.editorconfig` as a formatter.
The documentation only mentions configuring existing formatters. Can a new one be added?

### What is the significance of this feature?

strongly desired

### Additional details

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format
https://github.com/dotnet/format

**Comment by stevearc** [comment]
The [options section](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#options) documents all the possible configurations options for a formatter (under the `formatters` key). All you have to do is create a file under [lua/conform/formatters](https://github.com/stevearc/conform.nvim/tree/master/lua/conform/formatters) that returns a lua table with the values that make sense for your formatter. There are a [lot of example PRs](https://github.com/stevearc/conform.nvim/pulls?q=is%3Apr+is%3Aclosed) to look at as well. Note that some of them update the docs, but all you have to do is add the new formatter file. The docs will get updated automatically.
