### ISSUE TITLE
Feature request: Toggle format on save command

### ISSUE THREAD

**Issue by MariaSolOs** [stevearc/conform.nvim#39]
I just tried this and it works like a charm! Yet another amazing plugin <3

I do think it would be very helpful to have a `ToggleFormat` command for disabling/enabling format on save in the current buffer. This is particularly useful when working on external code that one doesn't want to format, and for momentarily disabling the formatter to avoid messing up with other people's code.

**Comment by MariaSolOs** [comment]
@stevearc thanks a lot for the recipes!

**Comment by gegoune** [comment]
I agree, great plugin, works very well and it's easy to use and configure.

In terms of toggling formatting- I found it to be better solution overall to have conditional formatting, based on presence of formatters' configuration files. Formatter's `condition` is great for that. 

Thanks for all your work on this plugin.

**Comment by redyf** [comment]
> I just tried this and it works like a charm! Yet another amazing plugin <3
> 
> I do think it would be very helpful to have a `ToggleFormat` command for disabling/enabling format on save in the current buffer. This is particularly useful when working on external code that one doesn't want to format, and for momentarily disabling the formatter to avoid messing up with other people's code.

I was looking for something similar and ended up doing this to toggle autoformatting and showing notifications for it:
```lua
    local conform = require("conform")
    local notify = require("notify")

    conform.setup({
      format_on_save = function(bufnr)
      -- Disable with a global or buffer-local variable
        if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
          return
        end
        return { timeout_ms = 500, lsp_fallback = true }
      end,
    })

    local function show_notification(message, level)
      notify(message, level, { title = "conform.nvim" })
    end

    vim.api.nvim_create_user_command("FormatToggle", function(args)
      local is_global = not args.bang
      if is_global then
        vim.g.disable_autoformat = not vim.g.disable_autoformat
      if vim.g.disable_autoformat then
        show_notification("Autoformat-on-save disabled globally", "info")
      else
        show_notification("Autoformat-on-save enabled globally", "info")
      end
      else
        vim.b.disable_autoformat = not vim.b.disable_autoformat
      if vim.b.disable_autoformat then
        show_notification("Autoformat-on-save disabled for this buffer", "info")
      else
        show_notification("Autoformat-on-save enabled for this buffer", "info")
        end
      end
    end, {
      desc = "Toggle autoformat-on-save",
      bang = true,
    })
```
Thank you for the idea @MariaSolOs @xfzv and great documentation for the plugin! @stevearc

**Comment by MariaSolOs** [comment]
@redyf happy to hear that you found this issue helpful (and came up with a neat solution)!

For future reference, [here's](https://github.com/MariaSolOs/dotfiles/blob/5e344230f63641e3e3540d489eb1d65d1dd60bf8/.config/nvim/lua/plugins/conform.lua) my current `conform` setup. I ended up setting it up in way that projects that are generally only owned by me (like my `dotfiles` and personal coding projects) have format-on-save enabled by default.

In addition, I also created [this mapping](https://github.com/MariaSolOs/dotfiles/blob/5e344230f63641e3e3540d489eb1d65d1dd60bf8/.config/nvim/lua/keymaps.lua#L16) to format the entire buffer using `conform` as my `formatexpr`.

**Comment by redyf** [comment]
That's really cool, thanks for sharing!
