### ISSUE TITLE
doc: How to format selection

### ISSUE THREAD

**Issue by realeinherjar** [stevearc/conform.nvim#40]
The docs says that `format()` "Defaults to current selection in visual mode":

https://github.com/stevearc/conform.nvim/blob/e9cc79fd723afccb8c0c16342b913fa6e96879b0/README.md?plain=1#L389

Yet, it is unclear on how to format a visual selection.

**Comment by stevearc** [comment]
The easiest way is if you have a keymap that runs `conform.format`, so

```lua
vim.keymap.set("", "<leader>f", function()
  require("conform").format({ async = true, lsp_fallback = true })
end)
```

If you're in visual mode when you use that keymap, it'll automatically pick up the range. Another way to do it would be to define a `Format` command that accepts a range. A recipe for that is here: https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#format-command

**Comment by Jendker** [comment]
Does the selection formatting work for you @realeinherjar? In my case it formats the whole file instead of just selection and if I press ‘:’ it will show the range indicators as if they were not used at all.

**Comment by realeinherjar** [comment]
Yes it does in visual mode.

**Comment by ReedMerrill** [comment]
The command as listed above doesn't work for me when there is a visual selection.

**Comment by bleacheda** [comment]
This [solution](https://github.com/stevearc/conform.nvim/issues/40#issuecomment-1719629250) doesn't work for me either.

**Comment by nixerr** [comment]
Formatting only a selected code doesn't work
