### ISSUE TITLE
bug: isort: error: argument --le/--line-ending: expected one argument

### ISSUE THREAD

**Issue by Barmaley0** [stevearc/conform.nvim#423]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

[conform.log](https://github.com/stevearc/conform.nvim/files/15467178/conform.log)

### Describe the bug

When applying isort formatting, an error occurs.
![Error isort](https://github.com/stevearc/conform.nvim/assets/133758633/63daacd5-bc0e-43de-956b-177740fa94ac)

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

When formatting any file that contains imports. This error occurs.

### Expected Behavior

![image](https://github.com/stevearc/conform.nvim/assets/133758633/b73c9d8f-f487-4254-bc1f-e63214ca4eb6)
Here is the config. When <leader>mp is pressed, all formatters work except isort.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

Has anyone encountered this and found a solution?

**Comment by vSkyper** [comment]
I encountered an identical bug, any solution?

**Comment by Barmaley0** [comment]
Found the cause of the failure. Black and Isort rule each other, and this leads to conflict. Therefore Isort is disabled. This argument can be corrected. I just haven't figured out how yet. You need to specify arguments in conform.nvim.🙄

**Comment by Barmaley0** [comment]
For now I've been able to get around the conflict by enabling the Isort and black settings. Although the line ending error remained in the ConformInfo manual. But everything works and there are no conflicts. You can also try using { "--profile", "black" } arguments. Now isort is not disabled. Conform works stably.

![image](https://github.com/stevearc/conform.nvim/assets/133758633/0226fe40-f17a-485f-bd11-4d3993885bd2)

**Comment by faea726** [comment]
I got the identical error.
Fixed it by re-rule the `isort` command (add one `-` to args).
A little shorter.
```
  formatters = {
    isort = {
      command = "isort",
      args = {
        "-",
      },
    },
  },
```
