### ISSUE TITLE
feature request: LSP fallback when formatting fails

### ISSUE THREAD

**Issue by abhinavnatarajan** [stevearc/conform.nvim#437]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Fallback to LSP formatting if `lsp_fallback` is set to true and formatting fails.

### Provide background

The current behaviour of `conform.format({lsp_fallback = true})` is to fallback to LSP formatting only if there are no formatters available for the buffer. If a formatter is available, LSP fallback will not be used even if formatting fails.

### What is the significance of this feature?

nice to have

### Additional details

This is simple enough to implement using the callback feature of `conform.format()`, but I find the current behaviour unintuitive/surprising. It would be nice to have LSP fallback upon failure as default behaviour (assuming `lsp_fallback = true`).

**Comment by stevearc** [comment]
If your formatter fails, it usually indicates there is either something wrong with your formatter or the file you are formatting. In either case, it seems like you would typically want to fix the root problem. Do you have a common case where your formatter fails and you do _not_ intend to fix it?

**Comment by Michaelpalacce** [comment]
This seems to happen a lot with bigger filex or with slower machines @stevearc I am having this issue quite a lot... When I do open a lot of projects conform is the first to start throwing, while without it things work fine

**Comment by abhinavnatarajan** [comment]
@stevearc apologies for the delayed response - there was a minor case where `stylua` failed to format correctly due to an issue in my environment, while `lua_ls` worked fine. I'm happy to close this issue though, since I generally agree with you and do not think this is a particularly useful addition to have.

**Comment by stevearc** [comment]
In that case, closing the issue.

@Michaelpalacce you mentioned conform is "throwing". I believe this issue is about normal format failures when there is an issue with the formatter, which will produce a notification. If you see conform throwing errors, please file a new issue with a repro.
