### ISSUE TITLE
feature request: Debug facility, show full command call

### ISSUE THREAD

**Issue by savchenko** [stevearc/conform.nvim#439]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

There doesn't seem to be a straightforward way to render resulting formatter command to `stdout`, etc.

I have tried `log_level = vim.log.levels.TRACE, but to no avail.

Could it be implemented?

### Provide background

Related to https://github.com/stevearc/conform.nvim/issues/386. I would like to debug the issue further, but there is not enough data to narrow-down the problem.

### What is the significance of this feature?

strongly desired

### Additional details

Will help user users, maybe even @stevearc himself :)

**Comment by stevearc** [comment]
Not sure what you mean by

> render resulting formatter command to `stdout`

If you set `log_level = vim.log.levels.TRACE` then you should get everything you need in the log file. `TRACE` should actually have more than you need; if all you want is the command that should show up at `DEBUG`. The path to the log file is shown in `:ConformInfo`
