### ISSUE TITLE
How to add shell command with pipe?

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/conform.nvim#44]
The way conform.nvim is set up, it seems slightly more complicated commands do not work.

For example, `shellcheck` [can be used to auto-fix some issues](https://github.com/koalaman/shellcheck/issues/1220#issuecomment-594811243) using this, effectively replacing `shellharden`:

```bash
shellcheck --format=diff my_file.sh | git apply
```

This works fine in the terminal, but the following config does not work:

```lua
formatters = {
	shellcheck = {
		command = "shellcheck",
		args = {"--format=diff", "$FILENAME", "|", "git", "apply" },
		stdin = false,
	},
},
```

I assume this is because in the background, conform.nvim uses `fn.system` with a list of strings, where pipes do not work. However, using `fn.system` with a single string does work fine, but passing a string to `args` results in an error.

Is there a way to make this work?

**Comment by ribru17** [comment]
Slightly off topic but I would also love a more generalized solution for passing arguments in general. Right now using `list_extend` works well enough unless a builtin formatter has `args` or `range_args` which are of type `function(ctx)`. In this case the user needs to basically copy the original function from the source, modify it to their needs, and then set that new function as the property. If there were some `with_args` or `extra_args` property implemented for the formatters this would be really nice, and maybe something similar could be done for this problem.

**Comment by stevearc** [comment]
@chrisgrieser can you take a look at #49 and see if it works for you? You can run the command in a shell by returning args as a string instead of a list. e.g.
```lua
args = "--format=diff $FILENAME | git apply"
```

**Comment by stevearc** [comment]
@ribru17 I have moved your comment to #50

**Comment by chrisgrieser** [comment]
thx, indeed the change works as it should, that is the using a string as `args`.

Only problem is, the related shell command does not play nice with temp files, it seems? 🤔 

```bash
shellcheck foobar.sh --format=diff
```

```diff
--- a/foobar.sh
+++ b/foobar.sh
@@ -1,1 +1,1 @@
-echo $SHELL
+echo "$SHELL"
```

Reading via stdin does not work here, since the diff is missing the filenames for `git apply`:

```diff
--- a/-
+++ b/-
```

Reading the file directly apparently has the issue that the temp files apparently cause some issue, too. Here the error message from `:ConformInfo`
```
07:38:23[ERROR] Formatter 'shellcheck' error: shellcheck: shellcheck: openBinaryFile: does not exist (No such file or directory)
error: zsh/Users/chrisgrieser/.config/zsh/.conform.6310933.foobar.sh: No such file or directory
```


for reference, here is the config I am using:
```lua
shellcheck = {
	command = "shellcheck",
	args = "shellcheck $FILENAME --shell=bash --format=diff | git apply",
	stdin = false,
},
```

---

In case this is not directly solvable, an alternative approach for this particular case might be for conform.nvim to use the diff resulting from `shellcheck --format=diff` and apply the changes, since it has some diff-applying method anyway?

**Comment by stevearc** [comment]
In the linked issue they mention using `| patch -p1`. Does that approach work better than `git apply`? Anything that relies on git is going to have problems with temp files.

**Comment by chrisgrieser** [comment]
hmm, using `| patch -p1` also does not seem to work 

```
11:40:15[INFO] Run shellcheck on /Users/chrisgrieser/.config/zsh/foobar.sh
11:40:15[DEBUG] Creating temp file /Users/chrisgrieser/.config/zsh/.conform.6310933.foobar.sh
11:40:15[DEBUG] Run command: shellcheck shellcheck /Users/chrisgrieser/.config/zsh/.conform.6310933.foobar.sh --shell=bash --format=diff | patch -p1
11:40:15[INFO] shellcheck exited with code 1
11:40:15[DEBUG] shellcheck stdout: nil
11:40:15[DEBUG] shellcheck stderr: { "shellcheck: shellcheck: openBinaryFile: does not exist (No such file or directory)", "" }
11:40:15[DEBUG] Cleaning up temp file /Users/chrisgrieser/.config/zsh/.conform.6310933.foobar.sh
11:40:15[ERROR] Formatter 'shellcheck' error: shellcheck: shellcheck: openBinaryFile: does not exist (No such file or directory)
```

**Comment by stevearc** [comment]
Try this definition:
```lua
formatters = {
  shellcheck = {
    command = "shellcheck",
    args = "$FILENAME --shell=bash --format=diff | patch -p1 $FILENAME",
    stdin = false,
  },
},
```

**Comment by chrisgrieser** [comment]
nice, that one works! Thx for the support. 🥳 

Guess that one can also be directly be added to the conform.nvim, I guess? (when #49 is merged)
