### ISSUE TITLE
bug: error: attempt to call field 'root' (a nil value)

### ISSUE THREAD

**Issue by radu781** [stevearc/conform.nvim#449]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-2752+g35239e977

### Operating system/version

Windows 10

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Error executing Lua callback: ...site\pack\packer\start\conform.nvim/lua/conform/util.lua:53: attempt to call field 'root' (a nil value)
stack traceback:
        ...site\pack\packer\start\conform.nvim/lua/conform/util.lua:53: in function 'cwd'
        ...site\pack\packer\start\conform.nvim/lua/conform/init.lua:633: in function 'get_formatter_info'
        ...te\pack\packer\start\conform.nvim/lua/conform/health.lua:144: in function 'append_formatters'
        ...te\pack\packer\start\conform.nvim/lua/conform/health.lua:163: in function 'show_window'
        ...site\pack\packer\start\conform.nvim/lua/conform/init.lua:165: in function <...site\pack\packer\start\conform.nvim/lua/conform/init.lua:164>

### Describe the bug

I can no longer use the plugin as it is intended, even a call to format fails
```lua
require("conform").format()
```

Full config:
```lua
local conform = require("conform")
conform.setup({
	formatters_by_ft = {
		lua = { "stylua" },
		-- Conform will run multiple formatters sequentially
		python = { "isort", "black" },
		-- Use a sub-list to run only the first available formatter
		-- javascript = { { "prettierd", "prettier" } },
		rust = { "rustfmt" },
        dart = { "dart format" },
	},
})

vim.keymap.set("n", "<leader>fr", function()
	local success = conform.format()
	local fidget = require("fidget")
	if success then
		fidget.notify("File formatted 󰸞")
	else
		fidget.notify("File format failed", vim.log.levels.ERROR, { annote = "File format failed" })
	end
end, { desc = "format file" })
```

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

1. `require("conform").format()`

### Expected Behavior

A couple of days ago this used to work, as in format the file without error

**Comment by stevearc** [comment]
You are on an old version of Neovim nightly that does not have `vim.fs.root`. I recommend upgrading to the released v0.10.0 version.

**Comment by GlennMm** [comment]
Hie im getting the same issue. 

NVIM v0.10.0-dev-f694d02
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by GLaDOS-418** [comment]
I was also getting this error even when I was using the nvim 0.10.0.
it turned out I had a wrong value for one of the settings.

**Comment by dcorral** [comment]
What was the wrong value? I am experiencing the same issue.

**Comment by radu781** [comment]
I only updated to a stable nvim 0.10 version and it worked
Pasting the config again:
```lua
local conform = require("conform")
conform.setup({
	formatters_by_ft = {
		lua = { "stylua" },
		-- Conform will run multiple formatters sequentially
		python = { "isort", "black" },
		-- Use a sub-list to run only the first available formatter
		-- javascript = { { "prettierd", "prettier" } },
		rust = { "rustfmt" },
		cpp = { "clang-format" },
		dart = { "dart format" },
	},
})

vim.keymap.set({ "n", "v" }, "<leader>fr", function()
	local success = conform.format()
	local fidget = require("fidget")
	if success then
		fidget.notify("File formatted 󰸞")
	else
		fidget.notify("File format failed", vim.log.levels.ERROR, { annote = "File format failed" })
	end
end, { desc = "format file or selection" })
```
```
❯ nvim -v
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```
@dcorral
