### ISSUE TITLE
feature request: New formatter - go templ fmt

### ISSUE THREAD

**Issue by timsofteng** [stevearc/conform.nvim#454]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be cool to have `templ fmt` formatter for go.templ files.

### What is the significance of this feature?

nice to have

### Additional details

https://github.com/a-h/templ

**Comment by stevearc** [comment]
We already have built-in support for `templ fmt`
https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/templ.lua
