### ISSUE TITLE
feature request(djlint): respect editorconfig/local buffer `tabstop`

### ISSUE THREAD

**Issue by mangkoran** [stevearc/conform.nvim#457]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

`djlint` could format buffer with [indent](https://djlint.com/docs/configuration/#indent) config based on editorconfig/local buffer `tabstop`

### Provide background

I found that `djlint` supports [indent](https://djlint.com/docs/configuration/#indent) config argument. It would be nice if this could be incorporated to `conform` config so that it could run `djlint` with config based on local buffer `tabstop` which is set based on editorconfig.

### What is the significance of this feature?

nice to have

### Additional details

I found a bit similar feature in `markdown-toc` [config](https://github.com/stevearc/conform.nvim/blob/797d1f622a23d4a21bb58218bdf5999a9beac4ef/lua/conform/formatters/markdown-toc.lua#L12) that could respect local buffer `tabstop` (although it's just check whether it's space or tab).

I would like to try to implement this feature so any guidance/suggestion is welcome.

Additionally, I think this feature could be implemented to all formatters that support indent config like this (however I have no idea what the formatters are).

**Comment by mangkoran** [comment]
I tried the following config (I use LazyVim) and it works.
```lua
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        htmldjango = { "djlint" },
      },
      formatters = {
        djlint = {
          args = function(self, ctx)
            local indent = vim.bo[ctx.buf].tabstop or 4
            return { "-", "--reformat", "--indent", indent }
          end,
        },
      },
    },
  },
```

**Comment by stevearc** [comment]
This looks like it would make a reasonable pull request
