### ISSUE TITLE
bug: typstmt project has been archived

### ISSUE THREAD

**Issue by Dioprz** [stevearc/conform.nvim#458]
### Neovim version (nvim -v)

.

### Operating system/version

.

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

.

### Describe the bug

Hi, 

I just want to let you know that [typstfmt](https://github.com/astrale-sharp/typstfmt) has been archived and you may want to remove it from the supported formatters (or maybe not, in that case feel free to close this immediately). 
Recommendation of the author is to use `[typstyle](https://github.com/Enter-tainer/typstyle)` instead, which is already supported by conform.nvim.

Thanks for the plugin, it is a fantastic tool!

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

.

### Expected Behavior

.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Thanks for the notice! I've marked it as deprecated
