### ISSUE TITLE
bug: shfmt ignores EditorConfig file

### ISSUE THREAD

**Issue by tigion** [stevearc/conform.nvim#492]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

macOS 14.5

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

-

### Describe the bug

Hi, the changes in #481 has the side effect, that in shfmt the EditorConfig file is ignored. Specifications such as `switch_case_indent = true` in the EditorConfig then no longer work.

> [!NOTE]
> If any EditorConfig files are found, they will be used to apply formatting options. `If any parser or printer flags are given to the tool, no EditorConfig formatting options will be used.` A default like -i=0 can be used for this purpose.
>
> from https://github.com/mvdan/sh/blob/68b762e/cmd/shfmt/shfmt.1.scd

I can add the `-ci` argument (stands for switch_case_indent = true), but I would be interested to know if ignoring the EditorConfig file is intentional.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by stevearc** [comment]
Unintentional; I don't think anyone involved in that PR were aware that shfmt pulled values from .editorconfig when it was present. I've added an exemption for when a .editorconfig is present
