### ISSUE TITLE
How to set up for Caddyfile?

### ISSUE THREAD

**Issue by mrlectus** [stevearc/conform.nvim#498]
I am trying to set this up to autoformat my Caddyfile, but when I save I get the error "WARNING: The file has been changed since reading it!!!"

This is my config
```lua
require("conform").setup({
  formatters_by_ft = {
  caddyfile = { "caddyfile" },
 },
  formatters = {
      caddyfile = {
        command = "caddy",
        args = { "fmt", "--overwrite" },
        stdin = true,
        cwd = require("conform.util").root_file({ "Caddyfile" }),
        require_cwd = true,
      }
  }
})

```

**Comment by mrlectus** [comment]
fixed with changing
`args = { "fmt", "--overwrite" },` which does print to stdout
to
`args = { "fmt"},` prints to std out

**Comment by wangweixuan** [comment]
The `-` argument can be used to tell caddy to read from stdin and avoid depending on `cwd`:
```lua
{
  command = "caddy",
  args = { "fmt", "-" },
  stdin = true,
}
```

**Comment by ahmafi** [comment]
Also you should better call it `caddy` instead of `caddyfile` because that's how treesitter knows it.
