### ISSUE TITLE
bug: stop_after_first cannot represent configs previously possible with sub-list syntax

### ISSUE THREAD

**Issue by fnune** [stevearc/conform.nvim#508]
### Neovim version (nvim -v)

0.10.1

### Operating system/version

Linux melian 6.8.12 #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024 x86_64 GNU/Linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

-

### Describe the bug

See this config:
```
formatters_by_ft = {
  python = { "ruff_fix", { "ruff_format", "black" } }
}
```

It cannot be represented by the new `stop_after_first` feature, because:

```lua
formatters_by_ft = {
  python = { "ruff_fix", "ruff_format", "black", stop_after_first = true }
}
```

...would not do the same (run `ruff_fix` always, run either `ruff_format` or `black`)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

-

### Expected Behavior

The new syntax allows for configurations representable by the previous one.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
There is [a recipe](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#run-the-first-available-formatter-followed-by-more-formatters) to achieve that functionality
