### ISSUE TITLE
How to configure isort to split imports

### ISSUE THREAD

**Issue by Barmaley0** [stevearc/conform.nvim#513]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Not log file

### Describe the bug

Not bug

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

Hello. Can you tell me how to make a setting to separate imports? At the moment it does not work.
![image](https://github.com/user-attachments/assets/c0dfe5b1-43e8-4d03-a732-4feaf624f171)

### Expected Behavior

There should be a division by packages
before
![image](https://github.com/user-attachments/assets/4c235866-3a46-4403-9981-3b7b357118a1)
after
![image](https://github.com/user-attachments/assets/785ca597-0492-4ab3-be3c-41e028faf5d7)

### Minimal example file

Tell me what I'm doing wrong?

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

How to set it up?

**Comment by stevearc** [comment]
You need to pass the sections in as an argument, presumably. I don't know where you got the idea to use the syntax you are using, but conform does not take arbitrary fields in the definition of the formatter. You can see the exact fields that are supported in the [options](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#options) documentation.

**Comment by Barmaley0** [comment]
I passed it as an argument but it doesn't work.

**Comment by stevearc** [comment]
Please check out the new docs I have written to aid with debugging: https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md
