### ISSUE TITLE
feature request: Switch currently attached formatter on the buffer. 

### ISSUE THREAD

**Issue by decipher-cs** [stevearc/conform.nvim#522]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

A way to switch the current formatter. Example: Something that can switch prettierd to eslint.

### Provide background

I use prettier for formatting and eslint for linting on all my projects. However, some of the projects that I contribute to use eslint as a linter as well as a formatter. 

**Workflow I'm tring to achieve:**
Now if I had an option to switch to eslint after opening a file then I could just select eslintd as a formatter. Or if I could disable conform then I could just do `ConformShutDown` which would stop conform and the LSP server for eslint would just handle the formatting.

**Current workflow:** 
I have 2 different bindings for formatting. One that uses conform and other that uses native lsp, which happens to be eslint.

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
I recommend checking out [this recipe](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save). Conform just exposes API methods and this one hook for format-on-save, but it's extremely flexible so you can define whatever commands you want to change the formatters or disable formatting entirely.
