### ISSUE TITLE
feature request: Only enable formatter if config exists

### ISSUE THREAD

**Issue by gracicot** [stevearc/conform.nvim#524]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I want to conditionally enable clangd only if `.clang-format` file exists, and disable auto format otherwise

### Provide background

I have some repos that are formatted automatically with clang format. I also have other repos that are not formatted by any tools, specifically because clang format don't support the style used in that repo. In that case, I prefer formatting code manually. I want to keep autoformatting those that specify a clang format config.

### What is the significance of this feature?

nice to have

### Additional details

Seems similar to #512, but conditional depending on the existence of a config file

**Comment by stevearc** [comment]
Set a `cwd` function and also `require_cwd = true` for `clang-format`. Here's an example of another formatter that does this:

https://github.com/stevearc/conform.nvim/blob/4e97712607bfdcadc097823339599e5bf05f97f9/lua/conform/formatters/sqlfluff.lua#L12-L19
