### ISSUE TITLE
bug: Passing `--indent-type Spaces` as arg to Stylua results in error

### ISSUE THREAD

**Issue by zaszi** [stevearc/conform.nvim#527]
### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Arch Linux

### Read debugging tips

- [X] I have read through the [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md).

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

14:43:51[DEBUG] Running formatters on /home/zaszi/.config/nvim/init.lua: { "stylua" }
14:43:51[INFO] Run stylua on /home/zaszi/.config/nvim/init.lua
14:43:51[DEBUG] Run command: { "/usr/bin/stylua", "--search-parent-directories", "--indent-type Spaces", "--stdin-filepath", "/home/zaszi/.config/nvim/init.lua", "-" }
14:43:51[DEBUG] Run default CWD: /home/zaszi/.config/nvim
14:43:51[INFO] stylua exited with code 2
14:43:51[DEBUG] stylua stdout: { "" }
14:43:51[DEBUG] stylua stderr: { "error: Found argument '--indent-type Spaces' which wasn't expected, or isn't valid in this context", "", "\tDid you mean '--indent-type'?", "", "\tIf you tried to supply `--indent-type Spaces` as a value rather than a flag, use `-- --indent-type Spaces`", "", "USAGE:", "    stylua --search-parent-directories --indent-type <INDENT_TYPE>", "", "For more information try --help", "" }
14:43:51[ERROR] Formatter 'stylua' error: error: Found argument '--indent-type Spaces' which wasn't expected, or isn't valid in this context

	Did you mean '--indent-type'?

	If you tried to supply `--indent-type Spaces` as a value rather than a flag, use `-- --indent-type Spaces`

USAGE:
    stylua --search-parent-directories --indent-type <INDENT_TYPE>

For more information try --help

### Describe the bug

Passing `--indent-type Spaces` to Stylua's arguments results in an error (see logs) and a broken formatter. This does not work no matter the position of the argument, whether prepending or appending, or as shown in the example `init.lua` rewriting the entire sequence.

According to Stylua's documentation and the error message itself, some configuration of this parameter *should* work. Running it as-is on the command line does indeed work as expected, formatting with spaces instead of tabs:

```
cd /home/zaszi/.config/nvim
cat /home/zaszi/.config/nvim/init.lua | /usr/bin/stylua --search-parent-directories --indent-type Spaces --stdin-filepath /home/zaszi/.config/nvim/init.lua -
```

Seems related to [366](https://github.com/stevearc/conform.nvim/issues/366).

I'm aware I could technically circumvent this problem by deferring this setting to a global `Stylua.toml` as per above issue, but that would result in maintaining and deploying a file outside of Neovim's configuration directory, which I would rather not do. In any case, passing an additional argument to an external binary seems like something that should just work, no?

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. Open a Lua file (such as init.lua) that is incorrectly formatted or formatted with tabs for indentation.
2. Save the buffer (or run Conform's formatter through any other means).

### Expected Behavior

Current buffer should be formatted with spaces instead of tabs.

### Minimal example file

`init.lua` itself can be used for testing.

### Minimal init.lua

```Lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
	spec = {
		-- Load conform.nvim
		{
			"stevearc/conform.nvim",
			event = { "BufWritePre" },
			cmd = { "ConformInfo" },
			opts = {
				log_level = vim.log.levels.DEBUG,
				formatters_by_ft = {
					lua = { "stylua" },
				},
				default_format_opts = {
					lsp_format = "fallback",
				},
				format_on_save = { timeout_ms = 500 },
				formatters = {
					stylua = {
						inherit = false,
						command = "/usr/bin/stylua",
						args = {
							"--search-parent-directories",
							"--indent-type Spaces",
							"--stdin-filepath",
							"$FILENAME",
							"-",
						},
					},
				},
			},
		},
	},
	install = { colorscheme = { "habamax" } },
	checker = { enabled = true },
})
```

**Comment by Frusadev** [comment]
It is ```lua
"--indent-type", "Spaces",```

**Comment by zaszi** [comment]
Well, I didn't expect the solution to be this simple yet I somehow missed it. Cheers @Frusadev, this works for me now:

```
args = {
    "--search-parent-directories",
    "--indent-type",
    "Spaces",
    "--stdin-filepath",
    "$FILENAME",
    "-",
},
```
