### ISSUE TITLE
bug: SqlFluff not respecting config 

### ISSUE THREAD

**Issue by Alt-iOS** [stevearc/conform.nvim#535]
### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

MacOS 14.6

### Read debugging tips

- [X] I have read through the [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md).

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

          2024-09-16 21:58:40[DEBUG] Running formatters on /Users/victor/side/backup_server/migrations/20240917021237_initial.up.sql: { "sqlfluff" }
          2024-09-16 21:58:40[INFO] Run sqlfluff on /Users/victor/side/backup_server/migrations/20240917021237_initial.up.sql
          2024-09-16 21:58:40[DEBUG] Run command: { "/Users/victor/.local/share/nvim/mason/bin/sqlfluff", "fix", "-" }
          2024-09-16 21:58:40[DEBUG] Run CWD: /Users/victor/side/backup_server
          2024-09-16 21:58:40[DEBUG] sqlfluff exited with code 0

### Describe the bug

When conform runs sqlfluff it doesnt seem to get local config files, while running the same binary `/.local/share/nvim/mason/bin/sqlfluff format` results in no errors. Basically it isnt detecting the `.sqlfluff` file in my `cwd` which is where the dialect gets setup

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. Setup sqlfluff with mason and conform
2. Write a query with sqlite specific dialect (i.e., `AUTOINCREMENT`)
3. Try to setup a .sqlfluff file, putting the dialect like this
```Toml
[sqlfluff]
dialect = sqlite
```
4. Run the formatter
5. Get the code diagnosis 
```
1. Line 1, Position 1: Found unparsable section: 'CREATE TABLE IF NOT EXISTS backup (\n    ...'
```

### Expected Behavior

Formatting works

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

The weird thing is, IF I call the tool directly on the terminal, it works as expected, but doesn't when using it through conform, leads me to believe there's something that may be blocking access to the config

**Comment by stevearc** [comment]
Have you followed all the steps in [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md)? Does running the command with `cat` in the terminal work as expected? Do the [raw calls to vim.system](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md#testing-vimsystem) work?

**Comment by Alt-iOS** [comment]
1. I followed the debugging tips (the log file output was in the op)
2. How do you mean with cat? Sorry I dont understand how you mean, if its just running` /.local/share/nvim/mason/bin/sqlfluff format` works fine and does seem to respects the config in the `.sqlfluff` file, if thats what you mean
3. It did work, I got a success with 0 status code because the tool does run, I can do it again if the output is needed, but was more or less `success -- table def`, and another `success`

**Comment by stevearc** [comment]
Follow the steps in [Testing the formatter](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md#testing-the-formatter). It uses `cat` to pass the file to stdin, which mimics what conform is doing.

I'm also confused a bit by the report. In your logs I see 
```
sqlfluff exited with code 0
```
but you say that there's some error message 
```
 Line 1, Position 1: Found unparsable section: 'CREATE TABLE IF NOT EXISTS backup (\n    ...'
```
Does sqlfluff print this error but exit with code 0? In your step `5. Get the code diagnosis`, what are you actually doing to see that error?

**Comment by Alt-iOS** [comment]
I am so sorry, its `nvim-lint` the one with the issue, at first it was both, but then I saw that sqlfluff was using some opts that I didnt set, it was `LazyVim` base config, after taking it out, I still got the error and assumed it was conform because of the old logs (should've cleared the file), after moving some more stuff I realized although I got the same error in the editor, it wasn't conform, the logs were clear now, it was `nvim-lint` (with the same error, because it also defaulted to the ansi dialect)
