### ISSUE TITLE
Prettier Timeout Issue with Custom Tab Width Configuration

### ISSUE THREAD

**Issue by niekdomi** [stevearc/conform.nvim#538]
I am encountering a `Formatter prettier timeout` error when trying to configure Prettier with a custom tab width of 4 spaces. I believe my configuration follows the documentation, but the formatter doesn't seem to work as expected with these custom settings.

Here is my current configuration:

```lua
return {
	"stevearc/conform.nvim",
	config = function()
		require("conform").setup({
			formatters_by_ft = {
				css = { "prettier" },
				graphql = { "prettier" },
				html = { "prettier" },
				javascript = { "prettier" },
				javascriptreact = { "prettier" },
				json = { "prettier" },
				lua = { "stylua" },
				markdown = { "prettier" },
				python = { "isort", "black" },
				rust = { "rustfmt", lsp_format = "fallback" },
				svelte = { "prettier" },
				typescript = { "prettier" },
				typescriptreact = { "prettier" },
				yaml = { "prettier" },
			},
			formatters = {
				prettier = {
					args = { "--tab-width", "4" },  -- Custom tab width configuration
				},
			},
			format_on_save = {
				lsp_fallback = true,
				async = false,
				timeout_ms = 500,
			},
		})
	end,
}
```

When I format a document using this configuration, I receive the following error message:  
`Formatter prettier timeout`.

Is there something wrong with how I'm configuring Prettier or passing custom arguments? Any help would be appreciated!

**Comment by ktkv419** [comment]
Just encountered this problem, setting prettier's arguments this way fixed the issue
```lua
  formatters = {
    prettier = {
      prepend_args = function()
        return { "--tab-width", "4" }
      end,
    },
  },
```

**Comment by hhheath** [comment]
@ktkv419 appreciate the suggestion! i was figuring out the same and landed here: 

```
    formatters = {
        prettier = {
            append_args = { "--tab-width", "4" },
        },
    },
```

cheers!
