### ISSUE TITLE
bug: prettierd config fails in monorepo (really specific)

### ISSUE THREAD

**Issue by wparsons-heins-globality** [stevearc/conform.nvim#545]
### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS 14.5

### Read debugging tips

- [X] I have read through the [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md).

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: /Users/william.parsons-heins/.local/state/nvim/conform.log
          2024-10-11 15:56:31[INFO] Run prettierd on /Users/william.parsons-heins/[monorepo-name]/packages/[package-name]/src/client.js
          2024-10-11 15:56:31[DEBUG] Run command: { "/Users/william.parsons-heins/.local/share/nvim/mason/bin/prettierd", "/Users/william.parsons-heins/[monorepo-name]/packages/[package-name]/src/client.js" }
          2024-10-11 15:56:31[DEBUG] Run CWD: /Users/william.parsons-heins/[monorepo-name]/packages/[package-name]
          2024-10-11 15:56:31[INFO] prettierd exited with code 1
          2024-10-11 15:56:31[DEBUG] prettierd stdout: { "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '[eslint-config]' imported from /Users/william.parsons-heins/[monorepo-name]/.prettierrc", "" }
          2024-10-11 15:56:31[DEBUG] prettierd stderr: { "" }
          2024-10-11 15:56:31[ERROR] Formatter 'prettierd' error: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '[eslint-config]' imported from /Users/william.parsons-heins/[monorepo-name]/.prettierrc

### Describe the bug

I'm using yarn berry for a monorepo and I have prettier installed and configured at the top-level of the workspace, all sub-packages are formatted using this install and configuration. Using `nodeLinker: node-modules`, so there will be `node_modules` in each package and the root.

When I run the formatter in the terminal it is fine. But when I run conform formatting inside neovim on a sub-package file it will always fail.

From what I can gather the prettierd configuration in conform will look for the nearest prettier configuration file to the file that is being formatted when setting the `cwd`, in this case it finds the `package.json` of the sub-package. The problem then seems to be that it will try to execute prettierd using the node_modules of that sub-package which in my case does not include the eslint config package that is installed at the root of the workspace.

Changing [this](https://github.com/stevearc/conform.nvim/blob/40d4e98fcc3e6f485f0e8924c63734bc7e305967/lua/conform/formatters/prettierd.lua#L15) to exclude `package.json` fixes the problem as it defers to the top-level prettier config.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. Using yarn berry monorepo with `nodeLinker` set to `node-modules` and a top-level prettier config that has a dependency
2. Try to format a file in a sub-package
3. See conform failure

### Expected Behavior

It can find the appropriate config and format.

### Additional context

Changing [this](https://github.com/stevearc/conform.nvim/blob/40d4e98fcc3e6f485f0e8924c63734bc7e305967/lua/conform/formatters/prettierd.lua#L15) to exclude `package.json` fixes the problem as it defers to the top-level prettier config

However, it would might be better that we check the package.json for a `"prettier"` key.

**Comment by ro0gr** [comment]
I had this part of the issue.

> check the package.json for a "prettier" key

And that's how my prettierd setup is currently looking(lazy):

```lua
    config = function(_, opts)
      local cwd = function(_, ctx)
        local byPrettierConfigFile = require('conform.util').root_file {
          '.prettierrc',
          '.prettierrc.json',
          '.prettierrc.yml',
          '.prettierrc.yaml',
          '.prettierrc.json5',
          '.prettierrc.js',
          '.prettierrc.cjs',
          '.prettierrc.mjs',
          '.prettierrc.toml',
          'prettier.config.js',
          'prettier.config.cjs',
          'prettier.config.mjs',
        }(_, ctx)

        if byPrettierConfigFile then
          return byPrettierConfigFile
        end

        -- TODO: recursively search for package.json + "prettier" condition until there is a proper package.json found
        local rootByPackageJSON = require('conform.util').root_file {
          'package.json',
        }(_, ctx)

        if rootByPackageJSON then
          return file_contains_pattern(rootByPackageJSON .. '/package.json', '"prettier":\\s\\{-}{') and rootByPackageJSON
        end
      end

      opts.formatters = {
        prettierd = {
          cwd = cwd,
        },
      }

      require('conform').setup(opts)
    end,
```

It does not support the monorepos case yet, but it seems doable.


I'm still going to give it a bit more love and find some time to work on a PR. Maybe we can discuss a good API for that at this point. 

It feels ehe easiest just to allow passing tables along the string file names, like

```lua
cwd = util.root_file({
    -- https://prettier.io/docs/en/configuration.html
    ".prettierrc",
    ".prettierrc.json",
    -- ...
    { "package.json", { containsRegex: '"prettier":\\s\\{-}{'} }
  }),
```
so in this case the `root_file` gets a bit smarter. Yes, it's naive, but I think it should cover most(all) of the possible cases.

An alternative solution could be to delegate full control to the useland by providing they a matcher function accepting the found file lines, which they can examine then. Smth like:

```lua
   -- ...
    { "package.json", { 
       matches: function (lines) 
         return ...
       end
    }
```
I'm not bit fan of that solution, cause if users will need to copy and justify it, it'd be too verbose. However, it simplifies the `root_file`.

Maybe there are some better ideas? Otherwise I'm going to give a try to the `containsRegex` PR in a foreseeable future.

**Comment by wparsons-heins-globality** [comment]
The first solution seems like a nice approach. 

Here's an example of how this `astrocommunity` pack reads a `package.json` key: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/typescript/init.lua

In their case they are reading the package.json if it exists, pulling out the keys and then checking for `prettier`. But ultimately your solution would do the same thing and be easier (could just call rg/grep?).

It might be easier to make a new util like `package_json_contains` to accept the regex then we'd have `cwd = util.root_file(...) or package_json_contains(...)`

**Comment by ro0gr** [comment]
I've started working on a PR. Here are some of my observations:

> Here's an example of how this astrocommunity pack reads a package.json key

From what I can see they check if there is `prettier` in the deps, but I believe the only thing that matters is whether the `prettier` config exists in the package.json, and binary itself is allowed to be installed at different parent(or global) location. Well, actually I believe `prettierd` is supposed to be installed globally only.

> It might be easier to make a new util like package_json_contains to accept the regex then we'd have cwd = util.root_file(...) or package_json_contains(...)

I thought about it. If scale the approach to other formatters it means conform would need to keep many functions to parse toml, yaml, etc,.. This feels bad from the maintanance perspective. And also users would need to learn all these new utils.

**Comment by wparsons-heins-globality** [comment]
Thanks for working on this ro0gr, much appreciated 👍

**Comment by ro0gr** [comment]
I think this should be resolved now with the recent https://github.com/stevearc/conform.nvim/releases/tag/v8.2.0 release. I expect you to be able to remove all your custom `prettierd` `cwd` logic(if any), and it should work just fine.
