### ISSUE TITLE
prettier: use global default configuration when no project configuration is found

### ISSUE THREAD

**Issue by saibayadon** [stevearc/conform.nvim#546]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Currently the prettier formatter is enabled when it detects a configuration file in the cwd (or a `package.json` file). That means that it can be enabled on projects with no defined configuration (which is intended and expected).

But, currently it only uses prettier's default configuration - I'd like to set up a global config file used for these scenarios (I know I could just copy the config into the folder, but sometimes I tinker with one off files and such that I still would like to be formatted without having to create or copy a config file first)

Ideally I'd like to have something stored in `~/.config/nvim/.prettierrc` and have that be used if no project-level configuration is found.

If there's another way to achieve this, please let me know.

### What is the significance of this feature?

nice to have

**Comment by ZktSn0w** [comment]
+1

**Comment by Jack-Barry** [comment]
I used to be able to do this with a "global" `~/.prettierrc`, but it's no longer working as before, which is a bit frustrating. According to their docs, Prettier does not support global config to avoid mismatched behavior when running the same repo on different machines, but for my org and use case it's fine to do it like this, and they seem to have set up the config resolving to allow for using a home folder config: https://github.com/prettier/prettier/issues/98.

For context, I use Conform and Prettier via LazyVim extras, and updated all deps recently, which is when these formatting shenanigans began for me - I'm supposing it's this change: https://github.com/stevearc/conform.nvim/commit/1a7ff54dcfbe1af139b11829c6d58f5ffab87707#diff-3733583e33c9f673770f1e10cc19fa4305341c8c7d0bb54ccd3b8a7b5a6f9e29R3

I got the old behavior for now by doing this override:

`.config/nvim/lua/plugins/conform.lua`

```lua
return {
  "stevearc/conform.nvim",
  opts = function(_, opts)
    opts.formatters.prettier = {
      cwd = require("conform.util").root_file({
        ".prettierrc",
        ".prettierrc.json",
        ".prettierrc.yml",
        ".prettierrc.yaml",
        ".prettierrc.json5",
        ".prettierrc.js",
        ".prettierrc.cjs",
        ".prettierrc.mjs",
        ".prettierrc.toml",
        "prettier.config.js",
        "prettier.config.cjs",
        "prettier.config.mjs",
        "package.json",
      }),
    }
  end,
}
```

Would be nice not to have to jump through those hoops though.

**Comment by ro0gr** [comment]
@Jack-Barry I'm sorry for the frustratuon but I don't understand your issue. As far as I understood you have prettierrc config at your user dir. It worked but it does not anymore?

I'd be happy to improve the current solution to mitigate such issues. I'd appreciate it if you could describe your issue in more details. Preferably in a dedicated issue with an example.

**Comment by Jack-Barry** [comment]
@ro0gr Sounds like you understand my issue - I was using `~/.prettierrc` before, but it no longer works. The override I provided makes it work again.

I added my notes here because this is precisely the kind of thing @saibayadon is looking for (I think): global config for Prettier. Putting it into the user's home folder aligns with what Prettier supports already, but currently doesn't seem to work out of the box with Conform.

I believe the change made in [this commit](https://github.com/stevearc/conform.nvim/commit/1a7ff54dcfbe1af139b11829c6d58f5ffab87707#diff-3733583e33c9f673770f1e10cc19fa4305341c8c7d0bb54ccd3b8a7b5a6f9e29L63) is the culprit.

Previously, `util.root_file` was called with the possible prettier config file names, and just returned the result of `vim.fs.root(ctx.dirname, files)`.

Now, `cwd` is used instead, which works a bit differently. I'm not sure how `vim.fs.root` with a function as the second argument works exactly - I'm not very well versed in Neovim/Lua development.

**Comment by ro0gr** [comment]
@Jack-Barry 
>  I was using ~/.prettierrc before, but it no longer works.

I can no see a reason why it doesn't. May you probably have external plugin dependencies defined there that don't resolve by nodejs(see https://github.com/stevearc/conform.nvim/issues/575#issuecomment-2474265074)? From what I can say, it should work if you satisfy the nodejs resolution algorithm.

> this is precisely the kind of thing @saibayadon is looking for (I think): global config for Prettier

I believe @saibayadon asks for another feature:

> Ideally I'd like to have something stored in ~/.config/nvim/.prettierrc and have that be used if no project-level configuration is found.

AFAIK this has never been supported, and if conform would support it ever a non-parent config logic should be implemented. But the home dir config should still work until your project is located somewhere deep in the home dir.

>  I'm not sure how vim.fs.root with a function as the second argument works exactly - I'm not very well versed in Neovim/Lua development.

no worries, I'm new to lua as well. If your case is different from the https://github.com/stevearc/conform.nvim/issues/575#issuecomment-2474265074 I'd really love to see a reproduction.

**Comment by saibayadon** [comment]
Yeah, what I'm looking for is a bit different - I want' to have a default configuration for one off files or projects that do not have a prettier configuration in their `cwd` - but honor the one in the projects if it exists (as different projects may have different code styles)

After diving into the codebase a bit here, I figured I could simply override the `args` function to return different arguments (including a configuration flag) depending on if there's a project-level configuration file, like so:

```lua
    formatters = {
      prettier = {
        args = function(self, ctx)
          local check_cwd = require("conform.util").root_file({
            ".prettierrc",
            ".prettierrc.json",
            ".prettierrc.yml",
            ".prettierrc.yaml",
            ".prettierrc.json5",
            ".prettierrc.js",
            ".prettierrc.cjs",
            ".prettierrc.mjs",
            ".prettierrc.toml",
            "prettier.config.js",
            "prettier.config.cjs",
            "prettier.config.mjs",
            "package.json",
          })

          local has_cwd = check_cwd(self, ctx) ~= nil

          if not has_cwd then
            return { "--stdin-filepath", "$FILENAME", "--config", "[full-path-for-config]" }
          end

          return { "--stdin-filepath", "$FILENAME" }
        end,
      },
    },
 ```
 
Not sure if it's the cleanest but it seems to be working.
 
I guess something like this could be added to the `prettier.lua` default configuration, but honestly given it's very niche I think doing it this way is probably better as it fits my particular needs so I'll go ahead and close the bug as I think this pretty much solves it.

**Comment by rodhash** [comment]
> I want to have a default configuration for one off files or projects that do not have a prettier configuration in their `cwd`, but honor the one in the projects if it exists

Exactly what I was looking for as well, not sure if things changed but having a global config in my homedir is working without touching `args`.
