### ISSUE TITLE
feat: Allow to set `formatexpr`

### ISSUE THREAD

**Issue by cryptomilk** [stevearc/conform.nvim#55]
As null-ls has been archived, I've started to look into alternatives for formatting. According to https://github.com/neovim/neovim/pull/24338 `:help formatexpr` should be used. By default the LSP implementation sets:

```
formatexpr=v:lua.vim.lsp.formatexpr()
```

It would be nice if conform would set it to a formatter lua functions it provides. The vim.lsp.formatexpr() is here:

https://github.com/neovim/neovim/blob/35e50d79c630b05f67a840ebe21b4043ba9a6066/runtime/lua/vim/lsp.lua#L2394-L2395

It would be nice to have a similar function in conform set it for configured filetype in conform. I can look into this in the next weeks if there is interest.

**Comment by stevearc** [comment]
Added. You can use it with `vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"`

**Comment by cryptomilk** [comment]
Thanks for implementing it so fast!

I'm using:

```lua
    local conform = require('conform')

    conform.setup()

    local pattern = {}
    if vim.fn.executable('stylua') == 1 then
        table.insert(pattern, 'lua')
        conform.formatters_by_ft.lua = { 'stylua' }
    end

    if vim.fn.executable('shfmt') == 1 then
        local cwd = vim.fn.getcwd()
        if string.find(cwd, 'samba', 1, true) then
            require('conform.formatters.shfmt').args =
                { '--posix', '--indent', '0', '-filename', '$FILENAME' }
        else
            require('conform.formatters.shfmt').args =
                { '--indent', '4', '-filename', '$FILENAME' }
        end

        table.insert(pattern, 'sh')
        conform.formatters_by_ft.sh = { 'shfmt' }
    end

    vim.api.nvim_create_autocmd('FileType', {
        pattern = pattern,
        callback = function(args)
            vim.api.nvim_buf_set_option(
                args.buf,
                'formatexpr',
                'v:lua.require("conform").formatexpr()'
            )
        end,
    })
```

This works great.

**Comment by cryptomilk** [comment]
Nice, thanks. You might want do add a few of those details to the readme!

**Comment by cryptomilk** [comment]
Actually, there is an issue if `vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"` is set for files not providing a formatter by conform or use LSP.

I can't format text with `gq` in a normal text files.

**Comment by stevearc** [comment]
Found out that this was because the LSP formatexpr doesn't fall back to the default formatexpr. Should be fixed now.

Also note that you can always get that default behavior using `gw`
