### ISSUE TITLE
bug: Injected formatter gets a runtime error when formatting a buffer with no treesitter parser

### ISSUE THREAD

**Issue by mehalter** [stevearc/conform.nvim#554]
### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Arch Linux

### Read debugging tips

- [X] I have read through the [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md).

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

2024-10-22 14:10:14[DEBUG] Running formatters on /home/mhalter3@icl.gtri.org/Documents/conform_test/some_random_file: { "injected" }
2024-10-22 14:10:14[INFO] Run injected on /home/mhalter3@icl.gtri.org/Documents/conform_test/some_random_file
2024-10-22 14:10:14[ERROR] error formatting log line: 'nil' args {
  n = 0
}

### Describe the bug

It looks like the `injected` formatter has  a line where it calls the `callback` function with just a string (https://github.com/stevearc/conform.nvim/blob/f5bd8419f8a29451e20bdb1061a54fe13d5c8de3/lua/conform/formatters/injected.lua#L152).

This in turn calls the `handle_result` function in `init.lua` (https://github.com/stevearc/conform.nvim/blob/f5bd8419f8a29451e20bdb1061a54fe13d5c8de3/lua/conform/init.lua#L470)

There it is expecting the `err` variable to be a table with an error code and a message. This fails when it is passed just a string because the notify function is called with `nil` instead of a string or a table.

I am guessing maybe the definition of the callback changed at one point and this might be a legacy approach to the callback. I noticed there are a few other places where a callback function is called with a string as well as the type definition says `callback: fun(err: nil|string, new_lines: nil|string[])`. So it seems there is some sort of discrepancy deeper than I was expecting.

Error Message:
```
Error executing vim.schedule lua callback: vim/_editor.lua:0: Invalid 'str': Expected Lua string                  
stack traceback:                                                                                                  
        [C]: in function 'nvim_err_writeln'                                                                       
        vim/_editor.lua: in function 'notify'                                                                     
        ...rm_test/.repro/plugins/conform.nvim/lua/conform/init.lua:18: in function ''                            
        vim/_editor.lua: in function <vim/_editor.lua:0>  
```

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. `nvim -u repro.lua some_random_file
2. `:lua require("conform").format()
3. See error

### Expected Behavior

There should be no error. Maybe in the case where some users may want injection formatting to be applied to all buffers it makes sense for it to actually fail relatively silently or intelligently just not try formatting if there is no treesitter parser for the buffer.

### Minimal example file

No content necessary

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"stevearc/conform.nvim",
		config = function()
			require("conform").setup({
				log_level = vim.log.levels.DEBUG,
				-- add your config here
				formatters_by_ft = {
					["*"] = { "injected" },
				},
			})
		end,
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Thanks for the report!
