### ISSUE TITLE
Overriding formatting options (not clear enough in the documentation how to do this properly)

### ISSUE THREAD

**Issue by Xenomorphy** [stevearc/conform.nvim#563]
I'm really unsure if this is the correct place to ask, but I am lost. I have checked other issues and the documentation but I couldn't find what I was looking for. I have plenty of neovim options set in my init.lua, such as tabstop or expandtab. I want ALL of these options to ALWAYS override anything the formatter tries to do. So if a formatter wants to enable expandtab I want it to stay disabled as per my config. I don't want to set up these options on a per formatter basis, I want it globally for everything conform tries to format. I bypassed specific filetype options such as zig.vim in ftplugins like this:

`vim.api.nvim_create_autocmd("BufEnter", {
	callback = function()
		Opts()
	end,
})
`

Is there something like that I can do for conform? I understand that these formatters are adhereing to a standard, just like the filetype options are, but I don't think someone elses standards should be forced on my personal editor configuration that I use recreationally.

**Comment by stevearc** [comment]
Candidly, this is a niche use case that I am not going to support. The way most people use formatters is for any given project, professional or recreational, they will pick some set of formatters to use and enforce them for all files in the repo, often using CI. If they want to tweak the formatting (spaces, tabs, indentation level, whatever), usually these formatters allow some amount of customization via config files which you can also check into the repo.

The use case of "I want the formatter to run, but then I want my vim options to override _some_ of that formatting" is just not common. If you want to try to implement something like it on your own, I'd recommend taking a look at the [trim_whitespace](https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/trim_whitespace.lua) formatter. You can define a formatter as a lua function and configure it to run _after_ all of your other formatters. Inside this function you could process the lines to convert tabs to spaces, change indentation levels, or anything else.
