### ISSUE TITLE
[solved] getting this error - Formatter failed. See :ConformInfo for details

### ISSUE THREAD

**Issue by icoderarely** [stevearc/conform.nvim#566]
Here is my config:
```lua
return {
  'stevearc/conform.nvim',
  event = { 'BufReadPre', 'BufNewFile' },
  config = function()
    local conform = require 'conform'

    conform.setup {
      formatters_by_ft = {
        lua = { 'stylua' },
        svelte = { 'prettierd', 'prettier', stop_after_first = true },
        -- astro = { { "prettierd", "prettier", stop_after_first = true } },
        javascript = { 'prettierd', 'prettier', stop_after_first = true },
        typescript = { 'prettierd', 'prettier', stop_after_first = true },
        javascriptreact = { 'prettierd', 'prettier', stop_after_first = true },
        typescriptreact = { 'prettierd', 'prettier', stop_after_first = true },
        json = { 'prettierd', 'prettier', stop_after_first = true },
        graphql = { 'prettierd', 'prettier', stop_after_first = true },
        -- java = { "google-java-format" },
        -- kotlin = { "ktlint" },
        -- ruby = { "standardrb" },
        markdown = { 'prettierd', 'prettier', stop_after_first = true },
        erb = { 'htmlbeautifier' },
        html = { 'htmlbeautifier' },
        bash = { 'beautysh' },
        -- proto = { "buf" },
        -- rust = { "rustfmt" },
        yaml = { 'yamlfix' },
        toml = { 'taplo' },
        css = { 'prettierd', 'prettier', stop_after_first = true },
        scss = { 'prettierd', 'prettier', stop_after_first = true },
        sh = { 'shellcheck' },
        go = { 'gofmt' },
      },
      format_on_save = {
        -- These options will be passed to conform.format()
        timeout_ms = 500,
        lsp_format = 'fallback',
      },
    }

    vim.keymap.set({ 'n', 'v' }, '<leader>pf', function()
      conform.format {
        lsp_fallback = true,
        async = false,
        timeout_ms = 1000,
      }
    end, { desc = 'Format file or range (in visual mode)' })
  end,
}
```

Output of what I get when I do :ConformInfo
![image](https://github.com/user-attachments/assets/3445339d-a24a-4afc-bb03-2cbb26536988)

**Comment by icoderarely** [comment]
does it have to do something with linter by any chance? 

just for reference pasting it here:
```lua
return {
  'mfussenegger/nvim-lint',
  event = {
    'BufReadPre',
    'BufNewFile',
  },
  config = function()
    local lint = require 'lint'

    lint.linters_by_ft = {
      javascript = { 'eslint_d' },
      typescript = { 'eslint_d' },
      javascriptreact = { 'eslint_d' },
      typescriptreact = { 'eslint_d' },
      svelte = { 'eslint_d' },
      -- kotlin = { "ktlint" },
      -- terraform = { "tflint" },
      -- ruby = { "standardrb" },
    }

    lint.linters.eslint_d = require('lint.util').wrap(lint.linters.eslint_d, function(diagnostic)
      -- try to ignore "No ESLint configuration found" error
      -- if diagnostic.message:find("Error: No ESLint configuration found") then -- old version
      -- update: 20240814, following is working
      if diagnostic.message:find 'Error: Could not find config file' then
        return nil
      end
      return diagnostic
    end)

    local lint_augroup = vim.api.nvim_create_augroup('lint', { clear = true })

    vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePost', 'InsertLeave' }, {
      group = lint_augroup,
      callback = function()
        lint.try_lint()
      end,
    })

    vim.keymap.set('n', '<leader>ll', function()
      lint.try_lint()
    end, { desc = 'Trigger linting for current file' })
  end,
}

```

**Comment by stevearc** [comment]
If you follow the bug report template, it will direct you to the documentation on [debugging](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md). The error looks like there is an issue with the prettierd command that is being run. You should use the logging to figure out what that command is, and then test it in your terminal to see if this is a conform issue or a prettierd issue.

**Comment by icoderarely** [comment]
I am unable to debug it :(, not sure what to do where. I read the doc.

**Comment by stevearc** [comment]
I am going to assume that you are relatively new at this, and give you some advice for any situation when you are asking for help.

1. You are asking for someone else to spend effort on your behalf. To maximize the chances that they do, make the amount of effort they have to spend as low as possible.
2. This means you should think from their perspective before you post. If I were that person, what information would I want? What would I ask you to try? Then proactively try those things, gather that information, and include it in your initial post. It can include details about your setup, things that you have tried, output you have seen, etc.
3. Oftentimes, there will be a standardized bug report template that outlines these exact steps for you. This is to ensure that the person you are asking will have enough context on your issue to provide help immediately, and doesn't have to spend the first several messages going back and forth asking for help. If such a template is provided, _use it_. Even if certain fields don't make sense for the issue you are reporting, fill everything out to the best of your ability.

Lastly, realize that no one is going to spend more effort trying to help you than you are willing to put forth yourself. If I see someone that fills out the bug report, proactively lists everything they have tried, narrowed down the repro to a minimal config and set of steps, and sends me all of this information in a clear format, I am not only in a better position to help, I am a lot more willing to spend my own time trying to reproduce the bug and help fix it. If all I get is a vague "Here's my config" and "I tried to debug but it didn't work," I am not inclined to spend any effort helping you.

If you are still stuck on this problem, please feel free to open a new issue and fill out the bug report template. I will happily help if I am provided enough information to.

**Comment by icoderarely** [comment]
I wasn’t sure what information to include and what to leave out. I thought providing the configuration details for this specific plugin would be enough. I might have made a mistake in the config itself—that was my best guess, and it turned out to be related. I didn’t go into detail because I honestly didn’t know what was to be included. Although have solved it, and I'll keep your reply in mind, really informative for me (yes I'm new).
