### ISSUE TITLE
feature request: provide something like `on_attach`

### ISSUE THREAD

**Issue by ferdinandrau** [stevearc/conform.nvim#569]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

This is just an idea – so if it's a bad one feel free to close this immediately. It would be useful to have the ability to do stuff like set buffer-specific settings for any buffer for which conform has formatter(s).

### Provide background

One example would be setting `formatexpr` to conform's, so that only buffers that actually use conform formatting have it set to that value.

I am aware that this "issue" can be easily solved with an autocmd. But there might be other things users could want to set.  😃

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Conform doesn't really have the same notion of "attaching" to a buffer like LSP. It mimics the `format` API from LSP, but it doesn't require starting a server or "opening" a buffer first, you just pass in the buffer to format. For that reason, I think this should be done by an autocmd in your own config if you need this kind of logic.
