### ISSUE TITLE
bug: How do I enable codespell for all languages?

### ISSUE THREAD

**Issue by jinzhongjia** [stevearc/conform.nvim#57]
### Neovim version (nvim -v)

nightly

### Operating system/version

arch linux

### Output of :ConformInfo

nothing

### Describe the bug

How do I enable `codespell` for all languages?
According to the example, only one file type can be matched

### Steps To Reproduce

nothing

### Expected Behavior

nothing

**Comment by stevearc** [comment]
You would do
```lua
require("conform").setup({
  formatters_by_ft = {
    ["*"] = { "codespell" },
  },
})
```

See `:help conform-options` for documentation on the `"*"` filetype

**Comment by siduck** [comment]
@stevearc are there another means by which we could automatically define a formatter for certain filetypes?

for example

`null_ls.builtins.formatting.prettier` 

and that'd set prettier for many filetypes 
![image](https://github.com/stevearc/conform.nvim/assets/59060246/28d2a7e1-0fbf-4185-beec-370d2adf77de)


but with conform, i'd have to write all those filetypes  = { "prettier" }

**Comment by stevearc** [comment]
Conform can't be configured like you're suggesting, where you pick a formatter and enable it for all relevant filetypes. The trouble is the behavior is undefined if you have multiple formatters enabled that support the same filetype. Do you want to run them both? Just the first one? What order?

So it's a bit more verbose, but the way to configure it is by explicitly setting the formatters you want to use per-filetype. If you have a bunch of types that use the same formatters, you can always use a loop to cut down on the boilerplate.

Small note: conform parses composite filetypes so if you specify `markdown` you don't need to also set `markdown.mdx`.

**Comment by siduck** [comment]
alright, i'll just loop for now!

```lua
local prettier_langs = { "javascript", "javascriptreact", "typescript", "typescriptreact", "css", "html", "json" }

local options = {
  formatters_by_ft = {
    lua = { "stylua" },
    sh = { "shfmt" },
  },
}

for _, lang in ipairs(prettier_langs) do
  options.formatters_by_ft[lang] = { "prettier" }
end

require("conform").setup(options)
```
