### ISSUE TITLE
documentation: Broken URL in clang-format meta-data.

### ISSUE THREAD

**Issue by prakharg8** [stevearc/conform.nvim#580]
The URL present in `lua/conform/formatters/clang-format.lua` is broken([https://www.kernel.org/doc/html/latest/process/clang-format.html](https://www.kernel.org/doc/html/latest/process/clang-format.html)). I suggest using this one instead -> [https://clang.llvm.org/docs/ClangFormat.html](https://clang.llvm.org/docs/ClangFormat.html).

**Comment by stevearc** [comment]
Thanks!
