### ISSUE TITLE
bug: prettier formatter chooses CWD according to location of `.prettierrc.json` rather than relative to `package.json`

### ISSUE THREAD

**Issue by insidewhy** [stevearc/conform.nvim#587]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-1238+g66bb1e577c

### Operating system/version

Linux (arch linux)

### Read debugging tips

- [X] I have read through the [debugging tips](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md).

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

2024-11-26 23:33:36[DEBUG] Run command: { "/home/james/projects/narwhal/lib/tools/chart-bot/node_modules/.bin/prettier", "--stdin-filepath", "/home/james/projects/narwhal/lib/tools/chart-bot/src/index.mts" }
2024-11-26 23:33:36[DEBUG] Run CWD: /home/james/projects/narwhal
2024-11-26 23:33:36[DEBUG] prettier exited with code 0

### Describe the bug

Our project is a monorepo, the `.prettierrc.json` is at the root of the monorepo.

As shown in the log, the `Run CWD` becomes the root of the monorepo. If a `.prettierrc.json` is created within the package itself the the `Run CWD` will be correct. Running prettier from the root of the monorepo can cause problems because the root of the monorepo may contain a `.prettierignore` file to ignore packages in the monorepo which are responsible for formatting themselves.

I believe it would be better to set the CWD according to the `package.json` above the file rather than the `.prettierrc.json` location above the file.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. touch .prettierrc.json
2. mkdir -p subproject
3. cd subproject
4. pnpm init
5. pnpm add -D prettier
6. touch index.ts
7. edit `index.ts` and save it.

### Expected Behavior

prettier should run with a CWD of `subproject` rather than a CWD above the subproject.

**Comment by ro0gr** [comment]
> Running prettier from the root of the monorepo can cause problems because the root of the monorepo may contain a .prettierignore file to ignore packages in the monorepo which are responsible for formatting themselves.

This doesn't sound clear to me. If a path is marked as ignored, it must be ignored, and that's what's happening AFAIU. Otherwise, it won't be possible to ignore a path from the monorepo root, that feels wrong.

Maybe I'm missing something. May you expand your steps to reproduce including the prettierignore to show the issue you experience?

**Comment by stevearc** [comment]
#564 changed the default behavior of prettier to choose the cwd with a `package.json` file only if that file contains a configuration for prettier. I think this is the more correct thing to do. If you still want your subprojects to be chosen as the cwd, you can
1. add a `prettier` config to them
2. add a `.prettierrc` or similar file in the subproject
3. override the value of `cwd` for the prettier formatter to be what it was before

**Comment by insidewhy** [comment]
Cool thanks for the update and advice, I updated my config to patch the `cwd` function since I guess the monorepo configurations I'm using are probably not the typical case for all users.
