### ISSUE TITLE
How to set cwd on formatter?

### ISSUE THREAD

**Issue by marcinjahn** [stevearc/conform.nvim#588]
I'm struggling with providing a valid config for csharpier:

```lua
return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      cs = { "csharpier" },
    },
    formatters = {
      csharpier = {
        cwd = require("conform.util").root_file(".csproj"),
        command = "dotnet csharpier",
        args = { "--write-stdout" },
      },
    },
  },
}
```

By default, conform uses csharpier from mason, but I'd rather want to use the version configured in a project that I'm working on, therefore I want to invoke `dotnet csharpier` from the directory where my project is located (`.csproj`).
What am I doing wrong?

`:ConformInfo` shows:

```
Formatters for this buffer:
LSP: roslyn
csharpier unavailable: Command not found
```

**Comment by stevearc** [comment]
The built-in formatter for csharpier uses the command `dotnet-csharpier` 
https://github.com/stevearc/conform.nvim/blob/62d5accad8b29d6ba9b58d3dff90c43a55621c60/lua/conform/formatters/csharpier.lua#L7-L9

It's actually important that the `command` is a single word, the name of the executable to be run. If this is actually invoked via `dotnet csharpier` (I'm not familiar with this tool), then you should change the configuration to be

```lua
command = "dotnet",
args = { "csharpier", "--write-stdout" },
```

**Comment by marcinjahn** [comment]
Right, it’s actually the same tool, the difference is that dotnet-csharpier invokes the version installed by mason(which for some reason is rather old), while ‚dotnet csharpier’ runs the version installed locally for a given project (via ‚dotnet tool’ utility).

to invoke the proper version of csharpier I need to invoke ‚dotnet tool’ from within the same directory where my .csproj is located.

**Comment by stevearc** [comment]
Did you try my suggestion?

**Comment by marcinjahn** [comment]
It seems to work fine after applying your suggested config. I did not set any cwd. What is the command's directory by default?

**Comment by stevearc** [comment]
If the cwd is not specified in the formatter config, it will default to Neovim's cwd (`:echo getcwd()`)
