### ISSUE TITLE
Option to format on leave/enter buffer

### ISSUE THREAD

**Issue by MannyFay** [stevearc/conform.nvim#592]
Hello,
I've searched for but I didn't found it..
Is there any option or way to run the formatter(s) if I leave or enter a buffer?
My nvim saves if I switch from insert mode to normal mode. Often the behavior is not so good, because lines are shifted on formatting but the cursor stays in the original line.

I've tried already some auto-commands, but none of them has worked.

Thanks by the way for this awesome plugin.

**Comment by stevearc** [comment]
An autocmd is the way to go here. Like the example in the README
```lua
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*",
  callback = function(args)
    require("conform").format({ bufnr = args.buf })
  end,
})
```

Except instead of BufWritePre you'll use BufLeave or BufEnter. If it's not working, use the provided [debugging tools](https://github.com/stevearc/conform.nvim/blob/master/doc/debugging.md#tools) to check the logs and see if you can find out what's going on. If that doesn't resolve it, feel free to post a minimal init.lua file that reproduces the issue (like the one provided in the bug report template) and I'll take a look.

**Comment by MannyFay** [comment]
Thank you @stevearc for your very fast reply :)

Yes, I've seen that before in the README.md but in this case I maybe don't understand it..
Is this autocmd not for automatically formatting the current buffer every time the buffer is saved?
It is the same behavior like the config shortcut you've provided in the README.md, not?
Here the shortcut example:  
```lua
require("conform").setup({
  format_on_save = {
    -- These options will be passed to conform.format()
    timeout_ms = 500,
    lsp_format = "fallback",
  },
})
```
If yes, and I understand it correctly, I'd like to avoid that because my nvim saves always if I switch from insert mode into normal mode. This leads in my case to unwanted behavior in the editing process, what was the origin of my thoughts and my question. I'd only like to format if I leave or jump into a buffer.

If no, and I understand it wrong, here is my actual conform.lua configuration file:
```lua
-------------------------------------------------------------------------------
-- Conform Plugin
-- https://github.com/stevearc/conform.nvim
-- Lightweight yet powerful formatter plugin for Neovim.
-------------------------------------------------------------------------------

return {
  'stevearc/conform.nvim',
  opts = {},
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    local conform = require("conform")

    conform.setup({
      formatters_by_ft     = {
        blade           = { "blade-formatter" },
        css             = { "prettierd" },
        graphql         = { "prettierd" },
        html            = { "prettierd" },
        json            = { "prettierd" },
        javascript      = { "prettierd" },
        javascriptreact = { "prettierd" },
        liquid          = { "prettierd" },
        lua             = { "stylua" },
        markdown        = { "prettierd" },
        python          = { "isort", "black" },
        shell           = { "shfmt" },
        svelte          = { "prettierd" },
        typescript      = { "prettierd" },
        typescriptreact = { "prettierd" },
        yaml            = { "prettierd" },
        ["*"]           = { "trim_whitespace" },
      },
      format_on_save       = {
        lsp_fallback = true,
        async        = false,
        timeout_ms   = 10000,
      },
      notify_on_error      = false, -- Conform will notify you when a formatter errors.
      quiet                = true,  -- Conform will suppress all output if quiet is true.
      notify_no_formatters = true,  -- Conform will notify you when no formatters are available for the buffer.
      formatters           = {
        prettierd = {
          condition = function()
            return vim.loop.fs_realpath(".prettierrc.js") ~= nil or vim.loop.fs_realpath(".prettierrc.mjs") ~= nil
          end,
        },
      },
    })


    vim.api.nvim_create_autocmd("BufWritePre", {
      pattern = "*",
      callback = function(args)
        require("conform").format({ bufnr = args.buf })
      end,
    })
    -- Create an augroup for the autocommands
    -- local group = vim.api.nvim_create_augroup("ConformAutoFormat", { clear = true })

    -- vim.api.nvim_create_autocmd({"BufEnter", "BufLeave"}, {
    --   group = group,
    --   callback = function(args)
    --     if vim.api.nvim_get_autocmds({ group = group, buffer = args.buf })[1] then
    --       require("conform").format({
    --         bufnr = args.buf,
    --         lsp_fallback = true,
    --         async = true,
    --         timeout_ms = 10000,
    --       })
    --     end
    --   end,
    -- })

    ---------------------------------------------------------------------------
    ----- Key Mappings

    vim.keymap.set({ "n", "v" }, "<leader>mp", function()
      conform.format({
        lsp_fallback = true,
        async = false,
        timeout_ms = 10000,
      })
    end, { desc = "Format file or range (in visual mode)" })
  end,
}
```

The parts I've tried so far (the rest that is there from my journey) are commented out. The part from your README.md is pasted above.

Sorry, if I've had steal your time for maybe something noobish like that :/

**Comment by stevearc** [comment]
I don't know what you're trying to do with that `if vim.api.nvim_get_autocmds({ group = group, buffer = args.buf })[1] then` conditional, but if you remove it the rest of that autocmd looks like I would expect. If you put that into your config, what do you see in your logs?

**Comment by MannyFay** [comment]
@stevearc I've tried a little around and now I've got it :)  

So I've commented this out in the `require("conform").setup({...})` part:
```lua
-- format_on_save = {
--   lsp_fallback = true,
--   async        = false,
--   timeout_ms   = 10000,
-- },
```

...and reworked the part with the `autocmd` we've talked about.  
Here is the (for me?!?) working solution, that I've put under the `require("conform").setup({...})` part:
```lua
local group = vim.api.nvim_create_augroup("ConformAutoFormat", { clear = true })

vim.api.nvim_create_autocmd({"BufEnter", "BufLeave"}, {
  group = group,
  callback = function(args)
    if vim.api.nvim_buf_is_valid(args.buf) and vim.bo[args.buf].modifiable and vim.bo[args.buf].buftype == "" then
      require("conform").format({
        bufnr = args.buf,
        lsp_fallback = true,
        async = true,
        timeout_ms = 10000,
      })
    end
  end,
})
```
Maybe, if this works for other people too, it can be a future feature? ...sorry, I don't know yet how to write something like that for you and pass it as pull request, so that you can decide if it is a good idea.

However, I thank you so much, that you have taken your time for helping me - awesome - because of that it works now :)
...and thanks again for this great plugin!!

**Comment by stevearc** [comment]
Glad you managed to figure it out! I don't think this makes sense as a feature, since it's kind of a niche use case and doesn't require much code to add the behavior yourself.
