### ISSUE TITLE
Questions: Did conform support format 'go' or 'bash' code in markdown

### ISSUE THREAD

**Issue by supengchuan** [stevearc/conform.nvim#597]
As described in the title, does Conform support formatting ‘bash’ code within Markdown? I've tried using injected mode, but it doesn't seem to work. If it is supported, could you provide a configuration? I would be very grateful.

golang code can be formated in markdown using goimports

**Comment by stevearc** [comment]
It's a small configuration issue; we've been looking up formatters by the treesitter language instead of the vim filetype. I've added a config option for this in the injected formatter, and provided a better default for bash. It should work as expected now.
