### ISSUE TITLE
bug: eslint_d failing in a way that disallows other formatters from running

### ISSUE THREAD

**Issue by Kazimazi** [stevearc/conform.nvim#72]
### Neovim version (nvim -v)

0.9.2

### Operating system/version

NixOS

### Output of :ConformInfo

```
06:56:07[ERROR] Formatter 'eslint_d' error: 
```

### Describe the bug

`eslint_d` being listed as formatter seems to cause rest of the formatters to fail too for given filetype. If I use `eslint` instead, formatting works as expected.

From cli both `eslint_d` and `eslint` fail if I ran it on some random js file since no configuration was provided... as expected.

### Steps To Reproduce

1. have `eslint_d` and `prettier` listed as formatters
2. have `eslint_d` ans `prettier` installed
3. run `require("conform").format({ async = true, lsp_fallback = true })` in javascript buffer

### Expected Behavior

`eslint_d` fails to format so falls back to `prettier`.

### Minimal lazy config for conform.nvim

```lua
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup {
        formatters_by_ft = {
          javascript = { "eslint_d", "prettier" },
        },
      }
      vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
      vim.keymap.set('', "<leader>f", function()
        require("conform").format({ async = true, lsp_fallback = true })
      end)
    end,
  },
```

**Comment by stevearc** [comment]
Anything in the logs about why `eslint_d` fails? What's the output of `:ConformInfo`?

**Comment by Kazimazi** [comment]
Only this: `06:56:07[ERROR] Formatter 'eslint_d' error: `

**Comment by stevearc** [comment]
That's interesting, it means the formatter is failing with no stdout or stderr. If you set the log level to DEBUG the logs should include the raw command with the exact arguments that are being run. Can you find those and try running them yourself in a shell?

The issue here is that `eslint_d` is failing, not that there's no fallback. We fallback when there are expected errors (e.g. the formatter is not installed), but not when there are these unexpected, runtime errors.

**Comment by stevearc** [comment]
Okay so eslint fails, and you're _expecting_ it to fail because there's no configuration file? So you want to run eslint when there's a configuration file, but you want to skip it if the configuration file is absent? If that is the case, I'd recommend this change:

```lua
require("conform.formatters.eslint_d").cwd = require("conform.util").root_file({
  ".eslint.js",
  ".eslint.cjs",
  ".eslint.yaml",
  ".eslint.yml",
  ".eslint.json",
})
require("conform.formatters.eslint_d").require_cwd = true
```

**Comment by Kazimazi** [comment]
> Okay so eslint fails, and you're expecting it to fail because there's no configuration file?
Yes.
> So you want to run eslint when there's a configuration file, but you want to skip it if the configuration file is absent?
Yes
Will try the snippet, thanks.

**Comment by stevearc** [comment]
Feel free to re-open if this does not fix your use case

**Comment by Kazimazi** [comment]
works :)
