### ISSUE TITLE
bug: incorrect range formatting with stylua

### ISSUE THREAD

**Issue by petobens** [stevearc/conform.nvim#89]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1240+g9afbfb4d64

### Operating system/version

Arch Linux

### Output of :ConformInfo

```
~ │Formatters for this buffer:                                                                                                                                                                                    │
~ │stylua ready (lua)                                                                                                                                                                                             │
```

### Describe the bug

Range formatting doesn't seem to work properly (at least with stylua)

### Steps To Reproduce

1. Open nvim with the minimal init.lua file
2. Open a foo.lua file with
```lua
local x=2
local y=3
local z=4
```
3. Select  2 lines as in the GIF and  press `,fc`
4. Those 2 lines don't get properly formatted

### Expected Behavior

After 4. get proper formatting (spaces around equal sign) for visually selected lines.

### Minimal init.lua

```Lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install and configure plugins
local plugins = {
    {
        'stevearc/conform.nvim',
        config = function()
            vim.o.formatexpr = [[v:lua.require('conform').formatexpr()]]
            require('conform').setup({
                format_on_save = {
                    timeout_ms = 200,
                    lsp_fallback = false,
                },
                notify_on_error = false,
                formatters_by_ft = {
                    lua = { 'stylua' },
                },
            })
            vim.keymap.set({ 'n', 'v' }, ',fc', function()
                require('conform').format({ async = true, lsp_fallback = false })
            end)
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

### Additional context

![conformvisual](https://github.com/stevearc/conform.nvim/assets/2583971/0b0834c8-960d-4adb-910c-8776077285e0)

**Comment by petobens** [comment]
Side note comment: I modify/extender my linter arguments with:
```lua
-- Formatter args
local utils = require('conform.util')
---- Json
utils.add_formatter_args(require('conform.formatters.jq'), { '--indent', '4' })
---- Lua
utils.add_formatter_args(
    require('conform.formatters.stylua'),
    { '--config-path=' .. vim.env.HOME .. '/.config/stylua.toml' }
)
---- Python
utils.add_formatter_args(
    require('conform.formatters.isort'),
    { '--settings-file=' .. vim.env.HOME .. '/.isort.cfg' }
)
```
I was wondering whether it was possible to define something like
```lua
local formatters = require('conform.formatters')
utils.add_formatter_args(formatters.jq, { '--indent', '4' })
```
but I get 
```
Failed to run `config` for conform.nvim

.../pedro/.config/nvim/lua/plugin-config/conform_config.lua:39: module 'conform.formatters' not found:
```
Any pointers? (sorry for not opening a new issue about this)

**Comment by stevearc** [comment]
This is just how stylua works. [From the readme](https://github.com/JohnnyMorganz/StyLua#formatting-ranges):

> Only whole statements lying within the range will be formatted. If part of a statement falls outside the range, the statement will be ignored.

You can verify this yourself by running the stylua command directly in the terminal and viewing the output.

As for your second question, I added a helper so that you can do `require("conform.formatters").jq`. It uses a bit of metatable magic, but in this case it seems pretty benign and not terribly confusing.

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
> As for your second question, I added a helper so that you can do require("conform.formatters").jq. It uses a bit of metatable magic, but in this case it seems pretty benign and not terribly confusing.

Hi! I saw that you just added the `prepend_args` config. Now my settings look like:
```lua
local formatters = require('conform.formatters')
formatters.jq.args = { '--indent', '4' }
require('conform').formatters.stylua =
    { prepend_args = { '--config-path=' .. vim.env.HOME .. '/.config/stylua.toml' } }
```
Is it possible to add the same helper/metatable-magic so as to rewrite the second line as:
```lua
formatters.stylua.prepend_args =
    { '--config-path=' .. vim.env.HOME .. '/.config/stylua.toml' }
```
Thanks in advance

**Comment by stevearc** [comment]
As an alternate proposal, what about

```lua
local conform = require("conform")
conform.formatters.jq = {
  args = { '--indent', '4' }
}
conform.formatters.stylua = {
  prepend_args = { '--config-path=' .. vim.env.HOME .. '/.config/stylua.toml' }
}
```

**Comment by petobens** [comment]
Make sense! Thanks
