### ISSUE TITLE
Formatter failed if there is an error on the buffer?

### ISSUE THREAD

**Issue by Nitesh000** [stevearc/conform.nvim#93]
### Question
Just want to ask if the formatter shows an error on saving if there is an error detected on the buffer?

- When I try to save a file (and of course format), if there is an error on the file then it shows an error. 
```bash
Error detected while processing BufWritePre Autocommands for "*":
Formatter failed. See :ConformInfo for details
```
- `:ConformInfo`:
```bash
          08:58:13[ERROR] Formatter 'prettier' error: [error] /home/yuu/My Space/developer/work/PWA/Gauge-PWA/app/page.js: SyntaxError: Missing semicolon. (8:7)
          [error]    6 | const HomeRoute = () => {
          [error]    7 |   const { isLoading, isLoggedIn, deviceId } = useContext(UserCtx);
          [error] >  8 |   cons router = useRouter();
          [error]      |       ^
          [error]    9 |   useEffect(() => {
          [error]   10 |     if (!isLoading) {
          [error]   11 |       if (!isLoggedIn) {

Formatters for this buffer:
LSP: tsserver
prettier ready (json, markdown, svelte, yaml, html, python, javascript, typescript, graphql, typescriptreact, javascriptreact, css)
```

> Very noob in configuring. Help much appreciated!

**Comment by stevearc** [comment]
Sorry, what is your question? You're asking "if the formatter shows an error on saving" and then you're also saying "if there is an error on the file then it shows an error". It sounds like you answered your own question?

**Comment by Nitesh000** [comment]
Sorry if I didn't make myself clear😅. I was saying if the file have an error(syntactical error), the formatter also prompting an error while saving. Is that how the plugin works or I have made some mistakes on my configuration?

**Comment by stevearc** [comment]
This is entirely up to the formatter. Some formatters will fail silently, some formatters will do their best even when they can't parse the contents. If the formatter throws an error, this plugin has no choice but to handle that error. Currently the way it works is that conform will display a notification for the error, then it should not display any more failure notifications until there is at least one success (to avoid noise). If you don't want to see even the single error notification, pass in `quiet = true` to the `format()` call

**Comment by Nitesh000** [comment]
Thanks for your time and info @stevearc ... much appreciated.

**Comment by blaind** [comment]
This can be solved by having a format_on_save function like below.

```lua
require("conform").setup({
        format_on_save = function(bufnr)
                local bufnr = vim.api.nvim_get_current_buf()
                local errors = vim.diagnostic.get(0, { severity = { min = vim.diagnostic.severity.ERROR } })

                if #errors > 0 then
                        return
                end

                return {
                        timeout_ms = 500,
                        lsp_fallback = true,
                }
        end,
})
```
