### ISSUE TITLE
Feature request: Add PHPCBF as another PHP formatter

### ISSUE THREAD

**Issue by opdavies** [stevearc/conform.nvim#94]

**Comment by stevearc** [comment]
PRs welcome! There are lots of great examples from other people adding formatters https://github.com/stevearc/conform.nvim/pulls?q=is%3Apr+is%3Aclosed

**Comment by opdavies** [comment]
I've tried adding it as a custom formatter, but it's not doing so correctly, so I'm unsure if I've done it correcty. If I can get it to work as expected, I'll happily create a PR.

**Comment by stevearc** [comment]
As you're trying it out, I would heartily recommend setting `log_level = vim.log.levels.TRACE` and tailing the log file. Should help a lot with seeing exactly what is going on.

**Comment by chrisbellboy** [comment]
I've also been trying to add `phpcbf` and have spent too many hours to count 🙈 but can't get it to work either. The error is usually:

`Error detected while processing BufWritePre Autocommands for "*"..BufWritePre Autocommands for "*":`

However, the log doesn't give a specific error, it just says:

`[ERROR] Formatter 'phpcbf' error: `

I've tried a super basic set up, with `stdin` ([which phpcbf supports](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#using-the-php-code-beautifier-and-fixer) via the `-` arg),  without `stdin`, and a million other ways. 

When I run the command that Conform is executing (debugged it to get the exact line) directly in the terminal, it works as expected. So I'm a bit stumped right now.

I'll keep thinking of more ways, but after seeing this and someone else [open and then close](https://github.com/stevearc/conform.nvim/pull/96) a PR for the same issue, it seems like the problem may lie deeper. 🤔

**Comment by chrisbellboy** [comment]
P.s in case it helps at all, this is a basic set up that works in null-ls:

```
args = {
    "-q",
    "--standard=PSR2",
    "--stdin-path=$FILENAME",
    "-",
}
```

**Comment by rawalplawit** [comment]
@chrisbellboy @opdavies I've created a PR adding support for phpcbf. Let me know if that works.

**Comment by chrisbellboy** [comment]
@rawalplawit you absolute legend, that worked! Thank you!

The `exit_codes = { 0, 1, 2 }` was it! 👏
